"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import SiteHeader from "../../components/SiteHeader";
import {villas} from "../../data/villas";

type Preferences={guests:number;budget:number;maxSaintTropezDistance:number|null;pool:boolean;seaView:boolean;quiet:boolean;beach:boolean;family:boolean};
const defaults:Preferences={guests:4,budget:10000,maxSaintTropezDistance:20,pool:true,seaView:true,quiet:true,beach:true,family:false};
function calculate(v:(typeof villas)[number],p:Preferences){let score=0;const matched:string[]=[],compromises:string[]=[];
 if(v.price<=p.budget){score+=25;matched.push("Dans votre budget")}else{const d=v.price-p.budget,r=d/p.budget;if(r<=.1){score+=18;compromises.push(`${d.toLocaleString("fr-FR")} € au-dessus`)}else if(r<=.2){score+=10;compromises.push("Budget légèrement dépassé")}else compromises.push("Budget dépassé")}
 if(v.guests>=p.guests){score+=v.guests-p.guests<=2?20:16;matched.push(`${v.guests} voyageurs`)}else{score-=5;compromises.push("Capacité insuffisante")}
 if(!p.pool)score+=15;else if(v.heatedPool){score+=15;matched.push("Piscine chauffée")}else if(v.pool){score+=11;matched.push("Piscine privée")}else compromises.push("Pas de piscine");
 if(!p.seaView)score+=15;else if(v.seaView){score+=15;matched.push("Vue mer")}else compromises.push("Pas de vue mer");
 if(!p.quiet)score+=10;else if(v.quiet){score+=10;matched.push("Cadre calme")}else compromises.push("Moins calme");
 if(!p.beach)score+=10;else if(v.beachDistance<=3){score+=10;matched.push(`${v.beachDistance} km de la plage`)}else if(v.beachDistance<=5){score+=7;matched.push(`${v.beachDistance} km de la plage`)}else compromises.push(`${v.beachDistance} km de la plage`);
 if(!p.family)score+=5;else if(v.guests>=6&&v.bedrooms>=3&&v.quiet){score+=5;matched.push("Adaptée aux familles")}else compromises.push("Moins adaptée aux familles");
 if(p.maxSaintTropezDistance!==null){if(v.saintTropezDistance<=p.maxSaintTropezDistance){matched.push(`${v.saintTropezDistance} km de Saint-Tropez`)}else{score-=12;compromises.push(`${v.saintTropezDistance} km de Saint-Tropez`)}}
 return {score:Math.max(0,Math.min(100,Math.round(score))),matched,compromises};}

const Toggle=({label,on,onChange}:{label:string;on:boolean;onChange:(v:boolean)=>void})=><button onClick={()=>onChange(!on)} className={`flex min-h-14 items-center justify-between border-b-2 px-0 text-left transition ${on?"border-[var(--lg-blue)] text-black":"border-black/15 text-black/45"}`}><span className="text-sm font-black uppercase tracking-[-.01em]">{label}</span><span className={`ml-6 grid h-7 w-7 place-items-center text-sm font-black ${on?"bg-[var(--lg-blue)] text-white":"border border-black/20"}`}>{on?"✓":"+"}</span></button>;

export default function MatchPage(){const [p,setP]=useState(defaults);const [show,setShow]=useState(false);const matches=useMemo(()=>villas.map(v=>({villa:v,...calculate(v,p)})).sort((a,b)=>b.score-a.score),[p]);
 const upd=<K extends keyof Preferences>(k:K,v:Preferences[K])=>setP(x=>({...x,[k]:v}));
 return <main className="min-h-screen bg-white text-black"><SiteHeader locale="fr" path="/match"/>
  <section className="lg-shell pb-12 pt-10 md:pb-20 md:pt-16"><p className="lg-kicker text-[var(--lg-blue)]">LE GOLFE / STAY</p><h1 className="mt-5 max-w-6xl text-[19vw] font-black uppercase leading-[.72] tracking-[-.08em] md:text-[150px]">LA BONNE<br/><span className="lg-accent">MAISON.</span></h1><div className="mt-9 grid gap-7 border-t-4 border-black pt-6 md:grid-cols-[1fr_auto] md:items-end"><p className="max-w-2xl text-xl font-black leading-8">Pas 200 villas. Quelques maisons qui correspondent vraiment à la façon dont vous voulez vivre le Golfe.</p><span className="lg-kicker">MATCHING / 01</span></div></section>

  <section className="bg-black text-white"><div className="lg-shell py-14 md:py-20"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="lg-kicker text-[#7fc4df]">VOTRE BRIEF</p><h2 className="mt-4 text-5xl font-black uppercase leading-[.88] tracking-[-.06em] md:text-7xl">DITES-NOUS CE QUI <span className="text-[#7fc4df]">COMPTE.</span></h2><p className="mt-6 max-w-sm text-sm font-semibold leading-6 text-white/55">On ne cherche pas la villa la plus spectaculaire. On cherche celle qui crée le moins de mauvais compromis pour votre séjour.</p></div>
   <div className="grid gap-8 bg-white p-6 text-black md:p-9"><div className="grid gap-7 sm:grid-cols-2"><label><span className="lg-kicker text-black/40">VOYAGEURS</span><div className="mt-3 flex items-center border-b-2 border-black pb-3"><button onClick={()=>upd("guests",Math.max(1,p.guests-1))} className="text-3xl font-black">−</button><span className="mx-auto text-5xl font-black tracking-[-.06em]">{p.guests}</span><button onClick={()=>upd("guests",Math.min(16,p.guests+1))} className="text-3xl font-black">+</button></div></label><label><span className="lg-kicker text-black/40">BUDGET / SEMAINE</span><div className="mt-3 border-b-2 border-black pb-3"><p className="text-5xl font-black tracking-[-.06em]">{p.budget.toLocaleString("fr-FR")} €</p><input aria-label="Budget" type="range" min="4000" max="20000" step="500" value={p.budget} onChange={e=>upd("budget",Number(e.target.value))} className="mt-4 w-full accent-[#0B4F6C]"/></div></label></div>
    <div className="border-t-2 border-black pt-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><span className="lg-kicker text-black/40">DISTANCE DE SAINT-TROPEZ</span><p className="mt-2 text-sm font-semibold text-black/55">Distance maximale souhaitée pour la maison.</p></div><p className="text-3xl font-black tracking-[-.05em]">{p.maxSaintTropezDistance===null?"PEU IMPORTE":`≤ ${p.maxSaintTropezDistance} KM`}</p></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-5">{([5,10,20,30,null] as const).map(distance=><button key={String(distance)} onClick={()=>upd("maxSaintTropezDistance",distance)} className={`min-h-12 border px-3 text-[10px] font-black uppercase tracking-[.12em] transition ${p.maxSaintTropezDistance===distance?"border-[var(--lg-blue)] bg-[var(--lg-blue)] text-white":"border-black/20 hover:border-black"}`}>{distance===null?"Peu importe":`≤ ${distance} km`}</button>)}</div></div>
    <div className="grid gap-x-8 md:grid-cols-2"><Toggle label="Piscine" on={p.pool} onChange={v=>upd("pool",v)}/><Toggle label="Vue mer" on={p.seaView} onChange={v=>upd("seaView",v)}/><Toggle label="Au calme" on={p.quiet} onChange={v=>upd("quiet",v)}/><Toggle label="Près de la plage" on={p.beach} onChange={v=>upd("beach",v)}/><Toggle label="Famille" on={p.family} onChange={v=>upd("family",v)}/></div>
    <button onClick={()=>setShow(true)} className="mt-2 min-h-16 bg-[var(--lg-blue)] px-6 text-left text-sm font-black uppercase tracking-[.14em] text-white">VOIR LES MAISONS QUI MATCHENT →</button>
   </div></div></div></section>

  {show&&<section className="lg-shell py-16 md:py-24"><div className="flex items-end justify-between border-b-4 border-black pb-5"><div><p className="lg-kicker text-[var(--lg-blue)]">VOTRE SÉLECTION</p><h2 className="mt-3 text-6xl font-black uppercase leading-[.82] tracking-[-.07em] md:text-8xl">{matches.slice(0,3).length} MAISONS.<br/>PAS PLUS.</h2></div><button onClick={()=>setShow(false)} className="lg-kicker underline underline-offset-4">Modifier le brief</button></div>
   <div className="mt-10 space-y-14">{matches.slice(0,3).map((m,i)=><article key={m.villa.id} className="grid gap-0 border-b-4 border-black pb-12 lg:grid-cols-[1.05fr_.95fr]"><Link href={`/villa/${m.villa.id}`} className="lg-image min-h-[420px]"><img src={m.villa.image} alt={m.villa.name}/></Link><div className="flex flex-col justify-between bg-[#f5f5f3] p-6 md:p-10"><div><div className="flex items-start justify-between gap-6"><div><p className="lg-kicker text-[var(--lg-blue)]">#{String(i+1).padStart(2,"0")} · {m.villa.location}</p><h3 className="mt-4 text-6xl font-black uppercase leading-[.78] tracking-[-.07em] md:text-8xl">{m.villa.name}</h3></div><div className="border border-[var(--lg-blue)] px-3 py-2 text-right"><p className="text-4xl font-black text-[var(--lg-blue)]">{m.score}</p><p className="text-[8px] font-black uppercase tracking-[.13em]">FIT / 100</p></div></div><p className="mt-7 max-w-xl text-base font-semibold leading-7 text-black/55">{m.villa.description}</p><div className="mt-5 inline-flex border border-black/20 px-3 py-2 text-[10px] font-black uppercase tracking-[.12em]">{m.villa.saintTropezDistance} KM DE SAINT-TROPEZ</div><div className="mt-8 grid gap-6 sm:grid-cols-2"><div><p className="lg-kicker">POURQUOI ÇA MARCHE</p>{m.matched.slice(0,4).map(x=><p key={x} className="border-b border-black/15 py-3 text-sm font-black">+ {x}</p>)}</div><div><p className="lg-kicker text-black/40">COMPROMIS</p>{(m.compromises.length?m.compromises:["Aucun compromis majeur détecté"]).slice(0,3).map(x=><p key={x} className="border-b border-black/15 py-3 text-sm font-black text-black/55">— {x}</p>)}</div></div></div><div className="mt-10 flex items-end justify-between gap-6 border-t border-black pt-5"><div><p className="text-4xl font-black tracking-[-.05em]">{m.villa.price.toLocaleString("fr-FR")} €</p><p className="lg-kicker text-black/35">PAR SEMAINE</p></div><Link href={`/villa/${m.villa.id}`} className="lg-btn bg-black text-white">VOIR LA MAISON →</Link></div></div></article>)}</div>
  </section>}
  {!show&&<section className="lg-shell py-16 md:py-24"><div className="lg-quote-box"><p className="lg-kicker">LE GOLFE TAKE</p><p className="mt-5 max-w-5xl text-5xl font-black uppercase leading-[.9] tracking-[-.06em] md:text-8xl">UNE MAISON N'EST PAS <span className="lg-accent">UN FILTRE.</span><br/>C'EST LE DÉBUT DU SÉJOUR.</p></div></section>}
 </main>}
