'use client';
import {useState} from 'react';
import {addDays,formatCalendarMonth,monthWindow} from '../lib/agendaCalendar';
import {datesBlocked,type VillaCalendar} from '../lib/villaAvailability';
export default function AvailabilityCalendar({calendar,today,fr=true}:{calendar:VillaCalendar;today:string;fr?:boolean}){
 const [month,setMonth]=useState(today.slice(0,7));const window=monthWindow(month)!;const offset=(new Date(window.from+'T12:00:00Z').getUTCDay()+6)%7;const length=Number(window.to.slice(-2));
 function move(amount:number){const d=new Date(month+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+amount);setMonth(d.toISOString().slice(0,7));}
 return <div className="mt-6 border border-black/20 bg-white p-4"><div className="flex items-center justify-between gap-2"><button type="button" onClick={()=>move(-1)} disabled={month<=today.slice(0,7)} aria-label={fr?'Mois précédent':'Previous month'} className="p-2 disabled:opacity-25">←</button><p className="text-sm font-black capitalize">{formatCalendarMonth(month,fr?'fr':'en')}</p><button type="button" onClick={()=>move(1)} disabled={month>=addDays(today,730).slice(0,7)} aria-label={fr?'Mois suivant':'Next month'} className="p-2 disabled:opacity-25">→</button></div><div className="mt-3 grid grid-cols-7 gap-1 text-center text-xs">{(fr?['Lu','Ma','Me','Je','Ve','Sa','Di']:['Mo','Tu','We','Th','Fr','Sa','Su']).map(day=><span key={day} className="py-2 font-bold">{day}</span>)}{Array.from({length:offset},(_,i)=><span key={`empty-${i}`}/>)}{Array.from({length},(_,i)=>{const day=`${month}-${String(i+1).padStart(2,'0')}`,blocked=datesBlocked(calendar,day,addDays(day,1)),past=day<today;return <span key={day} aria-label={`${day} — ${past?(fr?'date passée':'past date'):blocked?(fr?'nuit indisponible':'unavailable night'):(fr?'nuit ouverte, à confirmer':'open night, subject to confirmation')}`} className={`py-2 ${past?'text-black/25':blocked?'bg-[#071D2B] text-white':'bg-[#e8f1f3] text-[#0B4F6C]'}`}>{i+1}</span>;})}</div><div className="mt-4 flex flex-wrap gap-3 text-[10px]"><span><span className="mr-1 inline-block h-2 w-2 bg-[#071D2B]"/>{fr?'Nuit bloquée':'Blocked night'}</span><span><span className="mr-1 inline-block h-2 w-2 bg-[#e8f1f3]"/>{fr?'Nuit ouverte, à confirmer':'Open night, subject to confirmation'}</span></div></div>;
}
