'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {supabase} from '../lib/supabase';
import {loadHostDashboard,dashboardSummary,type HostDashboardData,type DashboardBooking} from '../lib/hostDashboard';
import {parisIsoDay} from '../lib/localCalendar';
import {formatCalendarDay} from '../lib/agendaCalendar';
import type {Property} from './HostDesk';
export default function HostOverview({fr,properties,mode='overview',onProperty,onCalendar,onInquiry,onListings,onConfirmed,onCreate}:{fr:boolean;properties:Property[];mode?:'overview'|'stays';onProperty:(p:Property)=>void;onCalendar:(p:Property)=>void;onInquiry:(id?:string)=>void;onListings:()=>void;onConfirmed:()=>void;onCreate:()=>void}){
 const [data,setData]=useState<HostDashboardData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[signedOut,setSignedOut]=useState(false);
 const generation=useRef(0),alive=useRef(true),actor=useRef(''),loadingLock=useRef(false);const today=parisIsoDay();
 async function load(){if(loadingLock.current)return;loadingLock.current=true;const ticket=++generation.current;setLoading(true);setError('');setData(null);try{const result=await loadHostDashboard(today);if(!alive.current||ticket!==generation.current)return;actor.current=result.userId;setSignedOut(false);setData(result);}catch(e){if(!alive.current||ticket!==generation.current)return;const login=e instanceof Error&&['SIGN_IN_REQUIRED','SESSION_CHANGED'].includes(e.message);setSignedOut(login);setError(login?(fr?'Connectez-vous pour retrouver les demandes et les séjours de votre compte.':'Sign in to find your account’s enquiries and stays.'):(fr?'Le tableau de bord n’a pas pu être chargé. Réessayez ; aucune donnée n’a été modifiée.':'The dashboard could not be loaded. Retry; no data was changed.'));}finally{loadingLock.current=false;if(alive.current&&ticket===generation.current)setLoading(false);}}
 useEffect(()=>{alive.current=true;void load();const {data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||(actor.current&&session?.user.id&&actor.current!==session.user.id)){generation.current++;actor.current='';setData(null);setLoading(false);setSignedOut(true);setError(fr?'Le compte a changé. Rechargez le tableau de bord.':'The account changed. Reload the dashboard.');}});return()=>{alive.current=false;generation.current++;subscription.unsubscribe();};},[]);
 const summary=data?dashboardSummary(data,today):null;
 const local=properties.filter(p=>!p.online&&p.id.startsWith('property-'));
 const pendingHomes=[...(data?.houses||[]).filter(p=>p.status==='draft'||!p.images.length||!(p.descriptionFr||p.description).trim()),...local.filter(p=>!data?.houses.some(h=>h.id===p.id))];
 const unavailable:Record<string,string>={inquiries:fr?'Demandes indisponibles : vérifiez la connexion et l’activation de la V50.':'Enquiries unavailable: check connection and V50 activation.',bookings:fr?'Séjours et propositions indisponibles : vérifiez la connexion et l’activation de la V56.':'Stays and proposals unavailable: check connection and V56 activation.',calendars:fr?'Calendriers indisponibles : vérifiez la connexion et l’activation de la V54.':'Calendars unavailable: check connection and V54 activation.'};
 function stay(b:DashboardBooking){const house=data?.houses.find(p=>p.id===b.listing_id);return <article key={b.inquiry_id} className="grid gap-4 border-b border-black/15 py-6 md:grid-cols-[1fr_1fr_auto] md:items-center"><div><p className="text-xs font-bold text-[var(--lg-blue)]">{b.arrival<=today?(fr?'EN COURS':'IN PROGRESS'):(fr?'À VENIR':'UPCOMING')}</p><h3 className="mt-2 text-2xl font-black tracking-tight">{house?.name||'Maison'}</h3><p className="mt-2 text-sm text-black/60">{b.guest||(fr?'Voyageur':'Guest')}{b.guests>0?` · ${b.guests} ${fr?'voyageurs':'guests'}`:''}</p></div><div><p className="text-sm font-bold">{formatCalendarDay(b.arrival,fr?'fr':'en')} → {formatCalendarDay(b.departure,fr?'fr':'en')}</p><p className="mt-2 text-lg font-black">{new Intl.NumberFormat(fr?'fr-FR':'en-GB',{style:'currency',currency:'EUR'}).format(b.total_price)} <span className="text-xs font-normal text-black/50">{fr?'prix convenu':'agreed price'}</span></p></div><button onClick={()=>onInquiry(b.inquiry_id)} className="lg-btn">{fr?'Voir le séjour':'View stay'} →</button></article>;}
 return <div className="py-10 md:py-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="lg-kicker text-[var(--lg-blue)]">{fr?'MON ACTIVITÉ':'MY ACTIVITY'}</p><h2 className="mt-4 text-4xl font-black tracking-[-.055em] md:text-6xl">{mode==='stays'?(fr?'LES SÉJOURS CONFIRMÉS.':'CONFIRMED STAYS.'):(fr?'TOUT AU MÊME ENDROIT.':'EVERYTHING IN ONE PLACE.')}</h2></div><button onClick={()=>void load()} disabled={loading} className="lg-btn">{loading?(fr?'Chargement…':'Loading…'):(fr?'Actualiser':'Refresh')} ↻</button></div>
 {loading&&<p role="status" className="mt-8 text-sm">{fr?'Chargement des informations du compte connecté…':'Loading the signed-in account’s information…'}</p>}
 {error&&<p role="alert" className="mt-7 border border-black/25 p-4 text-sm">{error}{signedOut&&<> <Link href={fr?'/fr/account':'/en/account'} className="font-bold underline">{fr?'Mon compte':'My account'}</Link></>}</p>}
 {data&&summary&&<><p className="mt-5 text-xs leading-6 text-black/50">{fr?'Compte connecté · Vue des 200 dernières maisons, des 200 dernières demandes et des 200 premiers séjours ou propositions encore à venir ou en cours. Actualisez après une modification.':'Signed-in account · Latest 200 homes, latest 200 enquiries and first 200 upcoming or ongoing stays or proposals. Refresh after changes.'}</p>{data.warnings.map(w=><p key={w} role="status" className="mt-3 border-l-2 border-[var(--lg-blue)] pl-3 text-xs leading-6">{unavailable[w]}</p>)}
 {mode==='overview'&&<><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
  {n:data.houses.length,label:fr?'Maisons du compte':'Account homes',detail:`${summary.published} ${fr?'en ligne':'online'} · ${summary.drafts} ${fr?'brouillons':'drafts'} · ${summary.paused} ${fr?'en pause':'paused'}`,click:onListings},
  {n:summary.requests?.length,label:fr?'Demandes à traiter':'Enquiries to handle',detail:fr?'Nouvelles ou en cours, pour des dates à venir':'New or in review, for upcoming dates',click:()=>onInquiry()},
  {n:summary.quotes?.length,label:fr?'Propositions à suivre':'Proposals to follow up',detail:fr?'Accord et confirmation à convenir':'Agreement and confirmation to arrange',click:()=>onInquiry()},
  {n:summary.confirmed?.length,label:fr?'Séjours confirmés':'Confirmed stays',detail:fr?'À venir ou déjà en cours':'Upcoming or already in progress',click:onConfirmed}
 ].map(c=><button key={c.label} onClick={c.click} className="border border-black/20 p-6 text-left transition hover:border-[var(--lg-blue)]"><p className="text-5xl font-black tracking-tight">{c.n??'—'}</p><p className="mt-4 text-sm font-bold">{c.label} ↗</p><p className="mt-2 text-xs leading-5 text-black/50">{c.detail}</p></button>)}</div>
 <section className="mt-12"><h3 className="lg-kicker">{fr?'À FAIRE':'TO DO'}</h3><div className="mt-5 border-t border-black/20">
 {summary.requests?.slice(0,3).map(r=><Task key={r.id} title={`${r.name} · ${r.propertyName}`} detail={fr?'Répondre à la demande':'Reply to the enquiry'} action={fr?'Ouvrir':'Open'} onClick={()=>onInquiry(r.id)}/>)}
 {summary.quotes?.slice(0,3).map(b=><Task key={b.inquiry_id} title={data.houses.find(p=>p.id===b.listing_id)?.name||'Maison'} detail={fr?'Proposition enregistrée : suivre l’accord du voyageur':'Saved proposal: follow up the guest’s agreement'} action={fr?'Suivre':'Follow up'} onClick={()=>onInquiry(b.inquiry_id)}/>)}
 {pendingHomes.slice(0,3).map(p=><Task key={p.id} title={p.name} detail={!p.online?(fr?'Annonce sur cet appareil, à préparer ou à mettre en ligne':'Listing on this device, to prepare or publish'):(fr?'Compléter l’annonce':'Complete the listing')} action={fr?'Modifier':'Edit'} onClick={()=>onProperty(p)}/>)}
 {summary.calendars?.slice(0,3).map(p=><Task key={p.id+'calendar'} title={p.name} detail={fr?'Disponibilités à renseigner et activer':'Availability to update and enable'} action={fr?'Calendrier':'Calendar'} onClick={()=>onCalendar(p)}/>)}
 {summary.requests?.length===0&&summary.quotes?.length===0&&pendingHomes.length===0&&summary.calendars?.length===0&&<p className="py-6 text-sm text-black/60">{fr?'Rien à traiter dans cette vue.':'Nothing to handle in this view.'}</p>}
 </div></section></>}
 <section className="mt-12"><div className="flex flex-wrap items-center justify-between gap-4"><h3 className="lg-kicker">{fr?'LES PROCHAINS SÉJOURS':'NEXT STAYS'}</h3>{mode==='overview'&&!!summary.confirmed?.length&&<button onClick={onConfirmed} className="text-xs font-bold underline">{fr?'Voir tous les séjours de cette vue':'View all stays in this view'}</button>}</div>{summary.confirmed===null?<p className="mt-5 text-sm text-black/60">{fr?'Les séjours ne sont pas disponibles pour le moment.':'Stays are currently unavailable.'}</p>:summary.confirmed.length?<div className="mt-5 border-t border-black/20">{(mode==='stays'?summary.confirmed:summary.confirmed.slice(0,5)).map(stay)}</div>:<p className="mt-5 border-y border-black/20 py-8 text-sm text-black/60">{fr?'Aucun séjour confirmé à venir ou en cours. Les briefs et exemples locaux ne sont pas des réservations.':'No upcoming or ongoing confirmed stay. Local briefs and samples are not bookings.'}</p>}</section>
 </>}
 {mode==='overview'&&<section className="mt-10 flex flex-wrap items-center justify-between gap-5 bg-[#071D2B] p-6 text-white"><div><p className="font-bold">{fr?'Préparer une nouvelle maison':'Prepare a new home'}</p><p className="mt-2 text-xs text-white/65">{local.length} {fr?'annonce(s) conservée(s) sur cet appareil':'listing(s) saved on this device'}</p></div><button onClick={onCreate} className="border border-white/50 px-4 py-3 text-xs font-bold">{fr?'Ajouter une maison':'Add a home'} +</button></section>}
 </div>;
}
function Task({title,detail,action,onClick}:{title:string;detail:string;action:string;onClick:()=>void}){return <article className="flex flex-wrap items-center justify-between gap-4 border-b border-black/15 py-5"><div><h4 className="text-lg font-black">{title}</h4><p className="mt-2 text-xs leading-5 text-black/55">{detail}</p></div><button onClick={onClick} className="lg-btn">{action} →</button></article>;}
