'use client';
import InquiryBooking from './InquiryBooking';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {supabase} from '../lib/supabase';
import {loadHostInquiries,saveInquiry} from '../lib/hostInquiryStore';
import {inquiryStatuses,inquiryLabel,filterInquiries,briefFromInquiry,inquiryReply,demoInquiries,type HostInquiry,type HostStay,type InquiryStatus} from '../lib/hostInquiries';
import {parisIsoDay} from '../lib/localCalendar';
import {formatCalendarDay} from '../lib/agendaCalendar';
export default function HostInquiryDesk({fr,onCreateBrief,briefIds,openInquiry}:{openInquiry?:{id?:string;token:number};fr:boolean;onCreateBrief:(stay:HostStay)=>boolean;briefIds:string[]}){
 const [rows,setRows]=useState<HostInquiry[]>([]),[mode,setMode]=useState<'idle'|'live'|'demo'>('idle'),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[status,setStatus]=useState<InquiryStatus|'all'>('all'),[query,setQuery]=useState('');
 const scope=useRef(''),generation=useRef(0);
 useEffect(()=>{const {data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||(scope.current&&scope.current!==session?.user.id)){generation.current++;scope.current='';setRows([]);setMode('idle');setNotice('');}});return()=>{generation.current++;subscription.unsubscribe();};},[]);
 useEffect(()=>{if(openInquiry)void load(openInquiry.id);},[openInquiry?.token]);
 async function load(inquiryId?:string){if(loading&&!inquiryId)return;setLoading(true);setError('');setNotice('');const round=++generation.current;try{const result=await loadHostInquiries(inquiryId);if(round!==generation.current)return;const {data:{user}}=await supabase.auth.getUser();if(round!==generation.current)return;if(user?.id!==result.userId)throw new Error('SESSION_CHANGED');scope.current=result.userId;setRows(result.rows);setStatus('all');setQuery('');setMode('live');}catch(e){if(round!==generation.current)return;setError(e instanceof Error&&e.message==='SIGN_IN_REQUIRED'?(fr?'Connectez-vous pour consulter vos demandes.':'Sign in to view your enquiries.'):(fr?'Chargement impossible. Vérifiez la connexion et l’activation de la V50 dans Supabase.':'Unable to load. Check your connection and V50 Supabase setup.'));}finally{if(round===generation.current)setLoading(false);}}
 function demo(){generation.current++;scope.current='';setRows(demoInquiries(parisIsoDay()));setMode('demo');setError('');setNotice('');setStatus('all');setQuery('');}
 async function update(row:HostInquiry,next:InquiryStatus,notes:string){const round=generation.current;if(mode==='demo'){setRows(previous=>previous.map(r=>r.id===row.id?{...r,status:next,owner_notes:notes}:r));return;}
 const changed=await saveInquiry(row,next,notes);if(round!==generation.current)throw new Error('SESSION_CHANGED');setRows(previous=>previous.map(r=>r.id===row.id?changed:r));}
 function create(row:HostInquiry){const stay=briefFromInquiry(row,mode==='demo');if(onCreateBrief(stay))setNotice(fr?'Brief créé dans Briefs sur cet appareil. Il ne confirme aucune réservation.':'Brief created in Briefs on this device. It does not confirm a booking.');else setError(fr?'Impossible de conserver le brief sur cet appareil.':'Unable to save the brief on this device.');}
 const filtered=filterInquiries(rows,status,query);
 return <div className="py-12"><p className="lg-kicker text-[var(--lg-blue)]">{fr?'DE LA DEMANDE AU SÉJOUR':'FROM ENQUIRY TO STAY'}</p><h2 className="mt-4 text-5xl font-black tracking-[-.055em] md:text-7xl">{fr?'VOS DEMANDES.':'YOUR ENQUIRIES.'}</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-black/60">{fr?'Retrouvez les demandes de vos maisons, gardez vos notes et préparez le séjour. Le statut de suivi ne réserve pas la maison.':'Find enquiries for your homes, keep notes and prepare the stay. A tracking status does not book the home.'}</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>void load()} disabled={loading} className="lg-btn lg-btn--dark">{loading?(fr?'Chargement…':'Loading…'):(fr?'Charger mes demandes':'Load my enquiries')} ↻</button><button onClick={demo} disabled={loading} className="lg-btn">{fr?'Tester avec des exemples':'Try sample enquiries'}</button>{mode!=='idle'&&<button onClick={()=>{generation.current++;scope.current='';setRows([]);setMode('idle');setNotice('');setError('');}} className="lg-btn">{fr?'Fermer les demandes':'Close enquiries'}</button>}</div>
 {mode==='demo'&&<p className="mt-6 border border-[var(--lg-blue)] p-4 text-sm font-bold">{fr?'DÉMONSTRATION — exemples fictifs, aucune demande envoyée et aucune modification de Supabase.':'DEMO — fictional examples, no enquiry sent and no changes to Supabase.'}</p>}{error&&<p role="alert" className="mt-5 border border-red-700 p-4 text-sm text-red-700">{error} <Link href={fr?'/fr/account':'/en/account'} className="underline">{fr?'Mon compte':'My account'}</Link></p>}{notice&&<p role="status" className="mt-5 border border-black/20 p-4 text-sm">{notice}</p>}
 {mode!=='idle'&&<><div className="mt-8 flex flex-wrap gap-3" aria-label={fr?'Filtrer les demandes':'Filter enquiries'}>{(['all',...inquiryStatuses] as const).map(key=><button key={key} aria-pressed={status===key} onClick={()=>setStatus(key)} className={`border px-4 py-3 text-xs font-bold ${status===key?'border-black bg-black text-white':'border-black/20'}`}>{key==='all'?(fr?'Toutes':'All'):inquiryLabel(key,fr)} · {key==='all'?rows.length:rows.filter(r=>r.status===key).length}</button>)}</div><label className="mt-5 block text-xs font-bold">{fr?'Rechercher un voyageur ou une maison':'Search a guest or home'}<input value={query} onChange={e=>setQuery(e.target.value)} type="search" maxLength={120} className="mt-2 w-full max-w-lg border border-black/30 p-3 text-base font-normal"/></label>{mode==='live'&&<p className="mt-4 text-xs text-black/50">{fr?'Demandes du compte connecté. « Charger mes demandes » retrouve les 100 dernières demandes.':'Signed-in account’s enquiries. “Load my enquiries” retrieves the latest 100.'}</p>}<div className="mt-8 space-y-6">{filtered.map(row=><InquiryCard key={row.id+mode} row={row} fr={fr} demo={mode==='demo'} onUpdate={update} onBrief={()=>create(row)} hasBrief={briefIds.includes(`${mode==='demo'?'demo:':''}${row.id}`)}/>)}</div>{filtered.length===0&&<p className="mt-8 border-y border-black/20 py-10 text-lg font-bold">{rows.length===0?(fr?'Aucune demande reçue pour le moment.':'No enquiries received yet.'):(fr?'Aucune demande ne correspond à ces filtres.':'No enquiries match these filters.')}</p>}</>}
 </div>;
}
function InquiryCard({row,fr,demo,onUpdate,onBrief,hasBrief}:{row:HostInquiry;fr:boolean;demo:boolean;onUpdate:(row:HostInquiry,status:InquiryStatus,notes:string)=>Promise<void>;onBrief:()=>void;hasBrief:boolean}){
 const [status,setStatus]=useState(row.status),[notes,setNotes]=useState(row.owner_notes),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);const lock=useRef(false);
 useEffect(()=>{setStatus(row.status);setNotes(row.owner_notes);},[row.status,row.owner_notes]);
 const dirty=status!==row.status||notes!==row.owner_notes;
 async function save(){if(lock.current||!dirty)return;lock.current=true;setBusy(true);setError('');setSaved(false);try{await onUpdate(row,status,notes);setSaved(true);}catch(e){setError(e instanceof Error&&e.message==='CONFLICT'?(fr?'Cette demande a changé ailleurs. Rechargez les demandes avant de réessayer. Vos notes saisies restent ici.':'This enquiry changed elsewhere. Reload before retrying. Your typed notes remain here.'):(fr?'La mise à jour n’a pas été confirmée. Vos notes saisies sont conservées ; réessayez.':'Update not confirmed. Your typed notes are preserved; retry.'));}finally{lock.current=false;setBusy(false);}}
 return <article className="border border-black/20 p-6 md:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="lg-kicker text-black/50">{row.propertyName}{row.location?` / ${row.location}`:''}</p><h3 className="mt-3 text-3xl font-black tracking-[-.04em]">{row.name}</h3><p className="mt-3 text-sm font-bold">{formatCalendarDay(row.arrival,fr?'fr':'en')} → {formatCalendarDay(row.departure,fr?'fr':'en')} · {row.guests} {fr?'voyageurs':'guests'}</p></div><span className="border border-black px-3 py-2 text-xs font-bold">{inquiryLabel(row.status,fr)}</span></div><p className="mt-6 whitespace-pre-line break-words text-sm leading-7 text-black/65">{row.message}</p>{!demo&&<div className="mt-5 flex flex-wrap gap-5 text-sm"><span className="break-all">{row.email}</span>{row.phone&&<span>{row.phone}</span>}</div>}
 <fieldset disabled={busy} className="mt-7 grid gap-5 border-t border-black/15 pt-6 md:grid-cols-[.4fr_.6fr]"><label className="text-xs font-bold">{fr?'Statut de suivi':'Tracking status'}<select value={status} onChange={e=>{setStatus(e.target.value as InquiryStatus);setSaved(false);}} className="mt-2 w-full border border-black/25 bg-white p-3 text-sm">{inquiryStatuses.map(s=><option key={s} value={s}>{inquiryLabel(s,fr)}</option>)}</select></label><label className="text-xs font-bold">{fr?'Notes internes':'Internal notes'}<textarea value={notes} maxLength={2000} rows={3} onChange={e=>{setNotes(e.target.value);setSaved(false);}} className="mt-2 w-full border border-black/25 p-3 text-sm font-normal"/><span className="mt-2 block text-[11px] font-normal text-black/50">{fr?'Visibles uniquement par le compte annonceur.':'Visible only to the advertiser account.'}</span></label></fieldset>
 {error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}{saved&&<p role="status" className="mt-4 text-sm">{demo?(fr?'Exemple mis à jour.':'Sample updated.'):(fr?'Suivi enregistré.':'Tracking saved.')}</p>}<div className="mt-5 flex flex-wrap gap-3"><button disabled={busy||!dirty} onClick={()=>void save()} className="lg-btn lg-btn--dark">{busy?(fr?'Enregistrement…':'Saving…'):(fr?'Enregistrer le suivi':'Save tracking')}</button>{!demo&&<a href={inquiryReply(row,fr)} className="lg-btn">{fr?'Préparer un e-mail':'Prepare an email'} ↗</a>}<button disabled={hasBrief||busy} onClick={onBrief} className="lg-btn">{hasBrief?(fr?'Brief déjà créé':'Brief already created'):(fr?'Créer le brief du séjour':'Create stay brief')} →</button></div><p className="mt-4 text-xs leading-6 text-black/50">{fr?'L’e-mail s’ouvre dans votre messagerie. Marquez Réponse effectuée après votre réponse ; le site n’envoie rien automatiquement.':'The email opens in your mail app. Mark Replied after replying; the site sends nothing automatically.'}</p>{!demo&&<InquiryBooking row={row} fr={fr}/>}</article>;
}
