'use client';
import {useEffect,useRef,useState} from 'react';
import {loadVillaBooking,actOnBooking,type BookingAction} from '../lib/villaBookingStore';
import {bookingReply,type VillaBooking} from '../lib/villaBooking';
import type {HostInquiry} from '../lib/hostInquiries';
import {supabase} from '../lib/supabase';
const errors:Record<string,[string,string]>={CALENDAR_LIMIT:['Le calendrier contient déjà 200 séjours à venir. Aucune nouvelle date n’a été bloquée.','The calendar already contains 200 upcoming stays. No new dates were blocked.'],NO_CONFIRMED_STAY:['Ce séjour n’est plus confirmé. Rechargez ses informations.','This stay is no longer confirmed. Reload its information.'],BOOKING_NOT_CONFIGURED:['La confirmation des séjours doit être activée par LE GOLFE.','Stay confirmation must be activated by LE GOLFE.'],SIGN_IN_REQUIRED:['Reconnectez-vous pour gérer ce séjour.','Sign in again to manage this stay.'],OWNER_REQUIRED:['Seul le compte propriétaire de cette annonce peut confirmer ce séjour.','Only this listing’s owner account can confirm the stay.'],BOOKING_CONFLICT:['Le séjour a changé ailleurs. Rechargez les informations enregistrées avant de recommencer.','The stay changed elsewhere. Reload the saved information before trying again.'],INVALID_QUOTE:['Indiquez le prix total en euros et les conditions (10 à 3 000 caractères).','Enter a total price in euros and terms (10 to 3,000 characters).'],CALENDAR_NOT_READY:['Activez et mettez à jour les disponibilités de cette maison avant de confirmer le séjour.','Enable and update this house’s availability before confirming the stay.'],DATES_UNAVAILABLE:['Ces dates ne sont plus libres. Un blocage ou un autre séjour empêche la confirmation.','These dates are no longer open. A block or another stay prevents confirmation.'],PAST_STAY:['Ce séjour a déjà commencé. La confirmation en ligne n’est plus possible.','This stay has already started. Online confirmation is no longer possible.'],AGREEMENT_REQUIRED:['Confirmez l’accord du voyageur avant de poursuivre.','Confirm the guest’s agreement before proceeding.'],QUOTE_REQUIRED:['Enregistrez une proposition avant de confirmer.','Save a proposal before confirming.'],BOOKING_ALREADY_CONFIRMED:['Ce séjour est déjà confirmé. Rechargez ses informations.','This stay is already confirmed. Reload its information.']};
export default function InquiryBooking({row,fr}:{row:HostInquiry;fr:boolean}){
 const [booking,setBooking]=useState<VillaBooking|null>(null),[price,setPrice]=useState(''),[conditions,setConditions]=useState(''),[loaded,setLoaded]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[agreed,setAgreed]=useState(false),[cancelAgreed,setCancelAgreed]=useState(false);
 const alive=useRef(true),generation=useRef(0),lock=useRef(false),actor=useRef('');
 function message(e:unknown){return errors[e instanceof Error?e.message:'']?.[fr?0:1]||(fr?'L’opération n’a pas été confirmée. Vos informations restent affichées. Rechargez le séjour pour vérifier son état avant de réessayer.':'The operation was not confirmed. Your details remain visible. Reload the stay to check its state before retrying.');}
 function apply(value:VillaBooking|null){setBooking(value);setPrice(value?String(value.total_price):'');setConditions(value?.conditions||'');setAgreed(false);setCancelAgreed(false);}
 async function load(){const ticket=++generation.current;setLoading(true);setLoaded(false);setError('');setNotice('');try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('SIGN_IN_REQUIRED');actor.current=user.id;const value=await loadVillaBooking(row.id);if(!alive.current||ticket!==generation.current)return;apply(value);setLoaded(true);}catch(e){if(alive.current&&ticket===generation.current)setError(message(e));}finally{if(alive.current&&ticket===generation.current)setLoading(false);}}
 useEffect(()=>{alive.current=true;void load();const {data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||(actor.current&&session?.user.id&&actor.current!==session.user.id)){generation.current++;actor.current='';apply(null);setLoaded(false);setNotice('');setError(errors.SIGN_IN_REQUIRED[fr?0:1]);}});return()=>{alive.current=false;generation.current++;subscription.unsubscribe();};},[row.id]);
 const dirty=!booking||Number(price)!==booking.total_price||conditions!==booking.conditions;
 async function action(kind:BookingAction){if(lock.current||!loaded)return;if(kind==='confirm'&&(dirty||!agreed))return;if(kind==='cancel'&&!cancelAgreed)return;lock.current=true;setBusy(true);setError('');setNotice('');const ticket=generation.current;try{const value=await actOnBooking(row.id,kind,booking,price,conditions,kind==='cancel'?cancelAgreed:agreed);if(!alive.current||ticket!==generation.current)return;apply(value);setNotice(kind==='quote'?(fr?'Proposition enregistrée. Vous pouvez préparer la réponse au voyageur.':'Proposal saved. You can prepare the guest reply.'):kind==='confirm'?(fr?'Séjour confirmé : les nuits sont bloquées dans le calendrier.':'Stay confirmed: the nights are blocked in the calendar.'):(fr?'Séjour annulé : ses nuits sont libérées. Les autres blocages sont conservés.':'Stay cancelled: its nights are released. Other blocks are retained.'));}catch(e){if(alive.current&&ticket===generation.current)setError(message(e));}finally{lock.current=false;if(alive.current)setBusy(false);}}
 const status=booking?.status==='confirmed'?(fr?'SÉJOUR CONFIRMÉ':'STAY CONFIRMED'):booking?.status==='cancelled'?(fr?'SÉJOUR ANNULÉ':'STAY CANCELLED'):(fr?'PROPOSITION DE SÉJOUR':'STAY PROPOSAL');
 return <section className="mt-7 border-t border-black/20 pt-6"><div className="flex flex-wrap items-center justify-between gap-3"><h4 className="lg-kicker text-[var(--lg-blue)]">{status}</h4><button type="button" disabled={loading||busy} onClick={()=>void load()} className="text-xs font-bold underline">{fr?'Recharger le séjour enregistré':'Reload saved stay'}</button></div>{loading&&<p role="status" className="mt-4 text-sm">{fr?'Chargement…':'Loading…'}</p>}{error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}{loaded&&<><fieldset disabled={busy||booking?.status==='confirmed'} className="mt-5 grid gap-5 md:grid-cols-[.35fr_.65fr]"><label className="text-xs font-bold">{fr?'Prix total du séjour (€)':'Total stay price (€)'}<input type="number" min="0" max="10000000" step="0.01" value={price} onChange={e=>{setPrice(e.target.value);setNotice('');}} className="mt-2 w-full border border-black/25 p-3 text-sm" placeholder="0"/></label><label className="text-xs font-bold">{fr?'Conditions proposées':'Proposed terms'}<textarea rows={4} minLength={10} maxLength={3000} value={conditions} onChange={e=>{setConditions(e.target.value);setNotice('');}} className="mt-2 w-full border border-black/25 p-3 text-sm font-normal" placeholder={fr?'Précisez ce que le prix comprend, les frais éventuels et les conditions convenues.':'Specify what the price includes, any extra fees and agreed terms.'}/></label></fieldset>
 {booking?.status!=='confirmed'&&<button type="button" disabled={busy||(!dirty&&booking?.status!=='cancelled')||!price.trim()||conditions.trim().length<10} onClick={()=>void action('quote')} className="lg-btn mt-5">{busy?(fr?'Enregistrement…':'Saving…'):(fr?'Enregistrer la proposition':'Save proposal')}</button>}
 {booking&&<a href={bookingReply(row,booking,fr)} className={`lg-btn mt-5 ${busy||dirty?'pointer-events-none opacity-40':''}`} aria-disabled={busy||dirty} tabIndex={busy||dirty?-1:undefined}>{fr?'Préparer la réponse avec le prix':'Prepare reply with price'} ↗</a>}
 {booking?.status==='quote'&&<div className="mt-6 border-t border-black/15 pt-5"><label className="flex gap-3 text-sm leading-6"><input type="checkbox" disabled={busy||dirty} checked={agreed} onChange={e=>setAgreed(e.target.checked)}/>{fr?'Le voyageur et moi avons convenu du prix et des conditions. Je confirme son accord.':'The guest and I agreed on the price and terms. I confirm their agreement.'}</label><button type="button" disabled={busy||dirty||!agreed} onClick={()=>void action('confirm')} className="lg-btn lg-btn--dark mt-4">{busy?(fr?'Vérification…':'Checking…'):(fr?'Confirmer le séjour et bloquer les dates':'Confirm stay and block dates')}</button></div>}
 {booking?.status==='confirmed'&&<details className="mt-6 border-t border-black/15 pt-5"><summary className="cursor-pointer text-sm font-bold">{fr?'Annuler ce séjour':'Cancel this stay'}</summary><label className="mt-4 flex gap-3 text-sm leading-6"><input type="checkbox" disabled={busy} checked={cancelAgreed} onChange={e=>setCancelAgreed(e.target.checked)}/>{fr?'Je confirme l’annulation de ce séjour et la libération de ses dates.':'I confirm cancellation of this stay and release of its dates.'}</label><button type="button" disabled={busy||!cancelAgreed} onClick={()=>void action('cancel')} className="lg-btn mt-4">{fr?'Annuler le séjour et libérer les dates':'Cancel stay and release dates'}</button></details>}
 <p className="mt-4 text-xs leading-6 text-black/50">{fr?'La proposition ne bloque pas les dates. La confirmation enregistre votre accord et bloque les nuits ; aucun paiement ni e-mail automatique.':'A proposal does not block dates. Confirmation records your agreement and blocks the nights; no payment or automatic email.'}</p></>}{notice&&<p role="status" className="mt-4 border border-black/20 p-3 text-sm font-bold">{notice}</p>}</section>;
}
