import Link from "next/link";
import SiteHeader from "./SiteHeader";
import SiteFooter from "./SiteFooter";
import Breadcrumbs from "./Breadcrumbs";
import CollectionSchema from "./CollectionSchema";
import StayFilters from "./StayFilters";
import {getPublishedVillas} from "../lib/publicVillas";
import { villas } from "../data/villas";
import { distanceSelections, villasWithin } from "../data/staySelections";
import type { Locale } from "../lib/i18n";
export default async function StayCollection({locale,selection}:{locale:Locale;selection?:typeof distanceSelections[number]}){
 const fr=locale==="fr";const path=`/${locale}/stay${selection?"/"+selection.slug:""}`;const remote=(await getPublishedVillas()).map(v=>({...v,image:v.photos[0]?.src||'',pool:v.amenities.includes('Pool'),descriptionEn:v.descriptionEn}));const all=[...remote,...villas.map(v=>({...v,amenities:[...(v.pool?['Pool']:[]),...(v.heatedPool?['Heated pool']:[]),...(v.seaView?['Sea view']:[])]}))];const list=all.filter(v=>!selection||(v.saintTropezDistance!==undefined&&v.saintTropezDistance<=selection.maxKm)).sort((a,b)=>(a.saintTropezDistance??Infinity)-(b.saintTropezDistance??Infinity));
 const title=selection?(fr?`Villas à ${selection.maxKm} km maximum de Saint-Tropez`:`Villas within ${selection.maxKm} km of Saint-Tropez`):(fr?"Villas dans le Golfe de Saint-Tropez":"Villas around the Golfe de Saint-Tropez");
 const intro=selection?(fr?selection.introFr:selection.introEn):(fr?"Comparez les maisons du catalogue selon leur commune, leur capacité et leurs équipements. Les sélections par distance permettent de garder Saint-Tropez comme repère sans perdre de vue le reste du séjour.":"Compare the catalog’s houses by destination, capacity and amenities. Distance selections use Saint-Tropez as a reference point while keeping the rest of your stay in view.");
 return <main><SiteHeader locale={locale} path={`/stay${selection?"/"+selection.slug:""}`}/><Breadcrumbs locale={locale} items={[{name:"LE GOLFE",path:`/${locale}`},{name:fr?"Villas":"Villas",path:`/${locale}/stay`},...(selection?[{name:`${selection.maxKm} km ${fr?"maximum":"maximum"}`,path}]:[])]}/><CollectionSchema name={title} path={path} items={list.map(v=>({name:v.name,path:`/villa/${v.id}`}))}/><section className="lg-shell py-12"><p className="lg-kicker">LE GOLFE / STAY</p><h1 className="mt-6 max-w-5xl text-5xl font-black md:text-7xl">{title}</h1><p className="mt-8 max-w-3xl text-lg leading-8">{intro}</p><p className="mt-5 max-w-3xl text-sm leading-6 text-black/55">{fr?"Distances déclarées dans les fiches, limite incluse. Elles ne donnent pas un temps de trajet ni la disponibilité des maisons ; confirmez ces informations avant de réserver.":"Distances as listed in the property guides, including the boundary. They do not indicate journey times or availability; confirm these details before booking."}</p><nav aria-label={fr?"Distance de Saint-Tropez":"Distance from Saint-Tropez"} className="mt-8 flex flex-wrap gap-3"><Link className="lg-btn" aria-current={!selection?"page":undefined} href={`/${locale}/stay`}>{fr?"Toutes les villas":"All villas"}</Link>{distanceSelections.filter(s=>all.some(v=>v.saintTropezDistance!==undefined&&v.saintTropezDistance<=s.maxKm)).map(s=><Link className="lg-btn" aria-current={selection?.slug===s.slug?"page":undefined} key={s.slug} href={`/${locale}/stay/${s.slug}`}>{s.maxKm} km {fr?"maximum":"maximum"} · {all.filter(v=>v.saintTropezDistance!==undefined&&v.saintTropezDistance<=s.maxKm).length}</Link>)}</nav><StayFilters villas={list} locale={locale}/><div className="mt-12 border-t border-black pt-8"><h2 className="text-3xl font-black">{fr?"Choisir selon votre séjour":"Choose around your stay"}</h2><p className="mt-4 max-w-2xl leading-7 text-black/60">{fr?"Pour comparer vos besoins — enfants, piscine, calme ou vue mer — utilisez le formulaire de recherche de maison.":"To compare your needs — children, pool, quiet or sea view — use the house matching form."}</p><div className="mt-6 flex flex-wrap gap-3"><Link className="lg-btn" href="/match">{fr?"Trouver ma maison":"Find my house · French form"} →</Link><Link className="lg-btn" href={`/${locale}/destinations`}>{fr?"Comparer les communes":"Compare destinations"} →</Link></div></div></section><SiteFooter locale={locale}/></main>;
}
