'use client';
import {villaAmenityGroups,essentialStayAmenities} from '../lib/villaAmenities';
import {useEffect,useState} from 'react';
import {loadVillaCalendars} from '../lib/villaCalendarStore';
import type {VillaCalendar} from '../lib/villaAvailability';
import {parisIsoDay} from '../lib/localCalendar';
import {addDays,formatCalendarDay} from '../lib/agendaCalendar';
import VillaCard from './VillaCard';
import type {Locale} from '../lib/i18n';
import {emptyStayFilters,filterStayVillas,stayAmenityOptions,type StayVilla,type StayFilters as Filters} from '../lib/stayFilters';
export default function StayFilters({villas,locale}:{villas:StayVilla[];locale:Locale}){
 const fr=locale==='fr';const [filters,setFilters]=useState<Filters>({...emptyStayFilters}),[open,setOpen]=useState(false);
 const locations=Array.from(new Set(villas.map(v=>v.location))).sort((a,b)=>a.localeCompare(b,locale));const [calendars,setCalendars]=useState<Record<string,VillaCalendar>>({}),[calendarLoading,setCalendarLoading]=useState(false),[calendarError,setCalendarError]=useState(false);const ids=villas.map(v=>v.id).join(',');
 useEffect(()=>{let active=true;setCalendars({});setCalendarError(false);if(!filters.arrival||!filters.departure){setCalendarLoading(false);return()=>{active=false;};}setCalendarLoading(true);void loadVillaCalendars(ids.split(',')).then(data=>{if(active)setCalendars(data);}).catch(()=>{if(active)setCalendarError(true);}).finally(()=>{if(active)setCalendarLoading(false);});return()=>{active=false;};},[ids,filters.arrival,filters.departure]);
 const datesSelected=!!(filters.arrival&&filters.departure);const list=filterStayVillas(villas,filters,calendars);const today=parisIsoDay();
 const field=(key:'location'|'guests'|'bedrooms'|'budget'|'arrival'|'departure',value:string)=>setFilters(previous=>({...previous,[key]:value}));
 const budgetLabel=(value:string)=>value==='quote'?(fr?'Prix sur demande':'Price on request'):`${fr?'Jusqu’à':'Up to'} ${new Intl.NumberFormat(fr?'fr-FR':'en-GB',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(value))} / ${fr?'semaine':'week'}`;
 const active=[...(filters.arrival||filters.departure?[{label:`${filters.arrival?formatCalendarDay(filters.arrival,locale,true):'…'} → ${filters.departure?formatCalendarDay(filters.departure,locale,true):'…'}`,remove:()=>setFilters(previous=>({...previous,arrival:'',departure:''}))}]:[]),...(filters.location?[{label:filters.location,remove:()=>field('location','')}]:[]),...(filters.guests?[{label:`${filters.guests} ${fr?'voyageurs':'guests'}`,remove:()=>field('guests','')}]:[]),...(filters.bedrooms?[{label:`${filters.bedrooms}+ ${fr?'chambres':'bedrooms'}`,remove:()=>field('bedrooms','')}]:[]),...(filters.budget?[{label:budgetLabel(filters.budget),remove:()=>field('budget','')}]:[]),...filters.amenities.map(a=>({label:stayAmenityOptions.find(([en])=>en===a)?.[fr?1:0]||a,remove:()=>setFilters(previous=>({...previous,amenities:previous.amenities.filter(x=>x!==a)}))}))];
 function amenityCheckbox(en:string,label:string){return <label key={en} className="flex cursor-pointer items-center gap-2 text-sm font-bold"><input type="checkbox" className="h-4 w-4 accent-black" checked={filters.amenities.includes(en)} onChange={e=>setFilters(previous=>({...previous,amenities:e.target.checked?[...previous.amenities,en]:previous.amenities.filter(a=>a!==en)}))}/>{fr?label:en}</label>;}
 const numberOptions=Array.from({length:20},(_,i)=>i+1).concat([30,40,50,60,70,80,90,100]);
 return <section aria-label={fr?'Filtrer les maisons':'Filter houses'} className="mt-10">
 <div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-2xl font-black">{fr?'Votre maison, selon vos envies':'Find the house that fits'}</h2><button type="button" className="lg-btn md:hidden" aria-expanded={open} aria-controls="stay-filter-panel" onClick={()=>setOpen(!open)}>{open?(fr?'Fermer les filtres':'Close filters'):(fr?'Filtrer':'Filter')}{active.length>0&&` (${active.length})`}</button></div>
 <div id="stay-filter-panel" className={`${open?'block':'hidden'} mt-5 border-y border-black py-6 md:block`}>
 <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
 <label className="block"><span className="lg-kicker">{fr?'Commune':'Location'}</span><select className="editor-input" value={filters.location} onChange={e=>field('location',e.target.value)}><option value="">{fr?'Toutes les communes':'All locations'}</option>{locations.map(location=><option key={location} value={location}>{location}</option>)}</select></label>
 <label className="block"><span className="lg-kicker">{fr?'Voyageurs':'Guests'}</span><select className="editor-input" value={filters.guests} onChange={e=>field('guests',e.target.value)}><option value="">{fr?'Peu importe':'Any capacity'}</option>{numberOptions.map(n=><option key={n} value={n}>{n} {fr?'voyageurs':'guests'}</option>)}</select></label>
 <label className="block"><span className="lg-kicker">{fr?'Chambres minimum':'Minimum bedrooms'}</span><select className="editor-input" value={filters.bedrooms} onChange={e=>field('bedrooms',e.target.value)}><option value="">{fr?'Peu importe':'Any number'}</option>{numberOptions.map(n=><option key={n} value={n}>{n}+</option>)}</select></label>
 <label className="block"><span className="lg-kicker">{fr?'Budget par semaine':'Weekly budget'}</span><select className="editor-input" value={filters.budget} onChange={e=>field('budget',e.target.value)}><option value="">{fr?'Tous les budgets':'All budgets'}</option>{['3000','5000','8000','10000','15000','20000','quote'].map(value=><option key={value} value={value}>{budgetLabel(value)}</option>)}</select></label>
 </div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="block"><span className="lg-kicker">{fr?'Arrivée':'Arrival'}</span><input type="date" min={today} value={filters.arrival} onChange={e=>setFilters(previous=>({...previous,arrival:e.target.value,...(previous.departure&&previous.departure<=e.target.value?{departure:''}:{})}))} className="editor-input"/></label><label className="block"><span className="lg-kicker">{fr?'Départ':'Checkout'}</span><input type="date" min={filters.arrival?addDays(filters.arrival,1):addDays(today,1)} value={filters.departure} onChange={e=>field('departure',e.target.value)} className="editor-input"/></label></div><p className="mt-3 text-xs leading-5 text-black/55">{fr?'Avec des dates, seules les maisons dont le calendrier est activé et ouvert pour tout votre séjour sont affichées. Confirmation du propriétaire requise.':'With dates, only houses with an enabled calendar open for your entire stay are shown. Owner confirmation is required.'}</p><fieldset className="mt-6"><legend className="lg-kicker">{fr?'Vos indispensables':'Your essentials'}</legend><div className="mt-4 flex flex-wrap gap-x-6 gap-y-4">{stayAmenityOptions.filter(([en])=>essentialStayAmenities.some(a=>a===en)).map(([en,label])=>amenityCheckbox(en,label))}</div></fieldset>
 <details className="mt-6 border-t border-black/15 pt-4"><summary className="cursor-pointer text-sm font-black">{fr?'Plus d’équipements':'More amenities'}{filters.amenities.filter(a=>!essentialStayAmenities.some(en=>en===a)).length>0&&` (${filters.amenities.filter(a=>!essentialStayAmenities.some(en=>en===a)).length})`}</summary><div className="mt-5 grid gap-6 sm:grid-cols-2">{villaAmenityGroups.map(group=>{const options=group.options.filter(([en])=>!essentialStayAmenities.some(a=>a===en));return options.length?<fieldset key={group.en}><legend className="text-xs font-black text-black/55">{fr?group.fr:group.en}</legend><div className="mt-3 flex flex-col gap-3">{options.map(([en,label])=>amenityCheckbox(en,label))}</div></fieldset>:null;})}</div></details>
 </div>
 <div className="mt-5 flex flex-wrap items-center gap-3">{active.map(item=><button key={item.label} type="button" onClick={item.remove} aria-label={`${fr?'Retirer le filtre':'Remove filter'} ${item.label}`} className="border border-black px-3 py-2 text-xs font-bold">{item.label} ×</button>)}{active.length>0&&<button type="button" className="px-2 py-2 text-sm font-bold underline" onClick={()=>setFilters({...emptyStayFilters})}>{fr?'Tout effacer':'Clear all'}</button>}</div>
 {(filters.arrival||filters.departure)&&!datesSelected&&<p className="mt-4 text-sm">{fr?'Choisissez une arrivée et un départ pour appliquer le filtre par dates.':'Choose arrival and checkout to apply the date filter.'}</p>}{datesSelected&&calendarError&&<p role="alert" className="mt-4 text-sm text-red-700">{fr?'Les calendriers sont indisponibles. Retirez le filtre par dates ou rechargez la page.':'Calendars are unavailable. Remove the date filter or reload the page.'}</p>}{datesSelected&&calendarLoading&&<p role="status" className="mt-4 text-sm">{fr?'Vérification des calendriers…':'Checking calendars…'}</p>}<p role="status" aria-live="polite" aria-atomic="true" className="mt-5 text-xs font-bold uppercase">{list.length} {fr?(list.length===1?'maison trouvée':'maisons trouvées'):(list.length===1?'house found':'houses found')}</p>
 {list.length?<div className="mt-6 grid gap-8 md:grid-cols-2 lg:grid-cols-3">{list.map(v=><VillaCard key={v.id} villa={v} locale={locale}/>)}</div>:<div className="mt-6 bg-neutral-100 p-8"><h3 className="text-2xl font-black">{fr?'Aucune maison avec ces critères':'No houses match these filters'}</h3><p className="mt-3 text-black/60">{fr?'Retirez un filtre pour élargir votre recherche.':'Remove a filter to broaden your search.'}</p><button type="button" className="lg-btn mt-5" onClick={()=>setFilters({...emptyStayFilters})}>{fr?'Tout effacer':'Clear all'}</button></div>}
 </section>;
}
