'use client';
import Link from 'next/link';
import {useState} from 'react';
import {villas} from '../data/villas';
import type {Locale} from '../lib/i18n';
export default function VillaComparison({items,locale}:{items:typeof villas;locale:Locale}){
 const fr=locale==='fr';const [selected,setSelected]=useState<string[]>([]),[copied,setCopied]=useState(false),[copyText,setCopyText]=useState('');const chosen=items.filter(v=>selected.includes(v.id));
 const rows:[string,(v:typeof villas[number])=>string][]=[['Commune',v=>v.location],[fr?'À partir de / semaine':'Starting price / week',v=>`${v.price.toLocaleString(fr?'fr-FR':'en-GB')} €`],[fr?'Voyageurs':'Guests',v=>String(v.guests)],[fr?'Chambres':'Bedrooms',v=>String(v.bedrooms)],[fr?'Salles de bain':'Bathrooms',v=>String(v.bathrooms)],[fr?'Piscine':'Pool',v=>v.heatedPool?(fr?'Chauffée':'Heated'):v.pool?(fr?'Oui':'Yes'):(fr?'Non renseignée':'Not listed')],[fr?'Vue mer':'Sea view',v=>v.seaView?(fr?'Oui':'Yes'):(fr?'Non renseignée':'Not listed')],[fr?'Cadre calme':'Quiet setting',v=>v.quiet?(fr?'Oui':'Yes'):(fr?'Non renseigné':'Not listed')],[fr?'Distance des plages':'Beach distance',v=>`${v.beachDistance} km`],[fr?'Distance de Saint-Tropez':'Distance from Saint-Tropez',v=>`${v.saintTropezDistance} km`]];
 async function share(){const text=items.map(v=>`${v.name} — ${v.location}\n${window.location.origin}/villa/${v.id}`).join('\n\n');try{await navigator.clipboard.writeText(text);setCopied(true);}catch{setCopyText(text);}}
 return <section className="mt-10 border-y border-black py-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h3 className="text-2xl font-black">{fr?'Comparer vos maisons':'Compare your homes'}</h3><p className="mt-3 text-sm text-black/55">{fr?'Choisissez deux ou trois villas pour les mettre côte à côte.':'Choose two or three villas to compare side by side.'}</p></div><button type="button" onClick={()=>void share()} className="lg-btn">{copied?(fr?'✓ Sélection copiée':'✓ Shortlist copied'):(fr?'Partager la sélection':'Share shortlist')}</button></div><p role="status" className="sr-only">{copied?(fr?'Liens copiés':'Links copied'):''}</p><div className="mt-5 flex flex-wrap gap-3">{items.map(v=><label key={v.id} className="flex items-center gap-2 border border-black/20 px-3 py-3 text-sm font-bold"><input type="checkbox" checked={selected.includes(v.id)} disabled={chosen.length>=3&&!selected.includes(v.id)} onChange={e=>setSelected(p=>e.target.checked?[...p,v.id]:p.filter(x=>x!==v.id))}/>{v.name}</label>)}</div>{chosen.length<2?<p className="mt-4 text-xs text-black/50">{fr?'Ajoutez au moins deux maisons à votre sélection pour les comparer.':'Save and select at least two homes to compare them.'}</p>:<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[540px] border-collapse text-left text-sm"><caption className="sr-only">{fr?'Comparaison de vos villas':'Villa comparison'}</caption><thead><tr><th scope="col" className="p-4">{fr?'Votre sélection':'Your shortlist'}</th>{chosen.map(v=><th key={v.id} scope="col" className="min-w-40 border-l border-black/15 p-4"><Link href={`/villa/${v.id}`} className="underline underline-offset-4">{v.name}</Link></th>)}</tr></thead><tbody>{rows.map(([label,value])=><tr key={label} className="border-t border-black/15"><th scope="row" className="p-4 font-semibold text-black/60">{label}</th>{chosen.map(v=><td key={v.id} className="border-l border-black/15 p-4 font-semibold">{value(v)}</td>)}</tr>)}<tr className="border-t border-black/15"><th scope="row" className="p-4">{fr?'Préparer le séjour':'Plan the stay'}</th>{chosen.map(v=><td key={v.id} className="border-l border-black/15 p-4"><Link href={`/villa/${v.id}#demande-sejour`} className="underline underline-offset-4">{fr?'Choisir mes dates':'Choose dates'} →</Link></td>)}</tr></tbody></table><p className="mt-4 text-xs text-black/50">{fr?'Tarifs de départ, disponibilités à confirmer. Les distances ne sont pas des temps de trajet.':'Starting prices, availability to be confirmed. Distances are not travel times.'}</p></div>}{copyText&&<label className="mt-5 block text-sm">{fr?'Copiez ces liens pour partager votre sélection :':'Copy these links to share your shortlist:'}<textarea readOnly value={copyText} onFocus={e=>e.target.select()} rows={5} className="mt-2 w-full border border-black p-3"/></label>}</section>;
}
