'use client';
import {useState} from 'react';
import {clampMapPoint,golfeMapCenter,mapPointPixels,pixelsMapPoint,type VillaMapLocation} from '../lib/villaMapLocation';
const width=768,height=384;
export default function VillaLocationMap({point,fr=true,onSelect}:{point?:VillaMapLocation;fr?:boolean;onSelect?:(latitude:number,longitude:number)=>void}){
 const [center,setCenter]=useState(point||golfeMapCenter),[zoom,setZoom]=useState(point?13:11),[failed,setFailed]=useState(false);const p=mapPointPixels(center.latitude,center.longitude,zoom),left=p.x-width/2,top=p.y-height/2;
 const tiles=[];for(let y=Math.floor(top/256);y<=Math.floor((top+height-1)/256);y++)for(let x=Math.floor(left/256);x<=Math.floor((left+width-1)/256);x++){let url=process.env.NEXT_PUBLIC_MAP_TILE_URL||'https://tile.openstreetmap.org/{z}/{x}/{y}.png';url=url.replace('{z}',String(zoom)).replace('{x}',String(x)).replace('{y}',String(y));tiles.push({x:x*256-left,y:y*256-top,url});}
 const marker=point?mapPointPixels(point.latitude,point.longitude,zoom):null;const zone=point?.mode==='approximate'?{nw:mapPointPixels(point.latitude+.005,point.longitude-.005,zoom),se:mapPointPixels(point.latitude-.005,point.longitude+.005,zoom)}:null;
 function pan(dx:number,dy:number){setCenter(clampMapPoint(pixelsMapPoint(p.x+dx,p.y+dy,zoom)));setFailed(false);}
 function select(latitude:number,longitude:number){const selected=clampMapPoint({latitude,longitude});onSelect?.(selected.latitude,selected.longitude);}
 return <div className="mt-5 border border-black/20 bg-[#e8f1f3]">
 <div className="relative"><svg viewBox={`0 0 ${width} ${height}`} className={`block w-full ${onSelect?'cursor-crosshair':''}`} role={onSelect?'button':'img'} tabIndex={onSelect?0:undefined} aria-label={onSelect?(fr?'Carte du Golfe : cliquez pour placer le repère. Entrée place le repère au centre ; les flèches déplacent la carte.':'Gulf map: click to place the location. Enter selects the center; arrow keys move the map.'):(point?.mode==='approximate'?(fr?'Zone approximative de la maison':'Approximate house area'):(fr?'Position exacte publiée par le propriétaire':'Exact location published by the owner'))} onKeyDown={e=>{if(!onSelect)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')pan(-128,0);if(e.key==='ArrowRight')pan(128,0);if(e.key==='ArrowUp')pan(0,-128);if(e.key==='ArrowDown')pan(0,128);if(e.key==='Enter'||e.key===' ')select(center.latitude,center.longitude);}} onClick={onSelect?e=>{const r=e.currentTarget.getBoundingClientRect();const selected=pixelsMapPoint(left+(e.clientX-r.left)/r.width*width,top+(e.clientY-r.top)/r.height*height,zoom);select(selected.latitude,selected.longitude);}:undefined}>
 {tiles.map(tile=><image key={tile.url} href={tile.url} x={tile.x} y={tile.y} width="256" height="256" onError={()=>setFailed(true)}/>)}
 {zone&&<rect x={zone.nw.x-left} y={zone.nw.y-top} width={zone.se.x-zone.nw.x} height={zone.se.y-zone.nw.y} fill="#0B4F6C" fillOpacity=".22" stroke="#0B4F6C" strokeWidth="3"/>}
 {marker&&!zone&&<g><circle cx={marker.x-left} cy={marker.y-top} r="12" fill="#071D2B" stroke="white" strokeWidth="3"/><circle cx={marker.x-left} cy={marker.y-top} r="3" fill="white"/></g>}
 </svg><div className="absolute right-3 top-3 flex flex-col gap-2"><button type="button" onClick={()=>{setZoom(z=>Math.min(point?.mode==='approximate'&&!onSelect?14:16,z+1));setFailed(false);}} disabled={zoom>=(point?.mode==='approximate'&&!onSelect?14:16)} className="h-9 w-9 border border-black/20 bg-white text-xl disabled:opacity-40" aria-label={fr?'Zoomer':'Zoom in'}>+</button><button type="button" onClick={()=>{setZoom(z=>Math.max(10,z-1));setFailed(false);}} disabled={zoom<=10} className="h-9 w-9 border border-black/20 bg-white text-xl disabled:opacity-40" aria-label={fr?'Dézoomer':'Zoom out'}>−</button></div></div>
 <div className="flex flex-wrap items-center justify-between gap-3 bg-white px-3 py-2"><div className="flex gap-1">{[['←',-160,0,fr?'Vers l’ouest':'West'],['↑',0,-120,fr?'Vers le nord':'North'],['↓',0,120,fr?'Vers le sud':'South'],['→',160,0,fr?'Vers l’est':'East']].map(([symbol,dx,dy,label])=><button type="button" key={String(symbol)} onClick={()=>pan(Number(dx),Number(dy))} aria-label={String(label)} className="border border-black/15 px-3 py-1 text-sm">{symbol}</button>)}{point&&<button type="button" onClick={()=>{setCenter(point);setFailed(false);}} className="px-2 text-xs font-bold underline">{fr?'Recentrer':'Recenter'}</button>}</div><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener" className="text-[10px] underline">© OpenStreetMap contributors</a></div>{failed&&<p role="status" className="bg-white px-3 pb-3 text-xs">{fr?'Le fond de carte est indisponible. Réessayez plus tard.':'Map tiles are unavailable. Try again later.'}</p>}
 </div>;
}
