'use client';
import {useState} from 'react';
import {normalizeMapLocation,type VillaMapLocation} from '../lib/villaMapLocation';
import VillaLocationMap from './VillaLocationMap';
export default function VillaLocationEditor({initial,district,fr}:{initial?:VillaMapLocation;district?:string;fr:boolean}){
 const [point,setPoint]=useState(()=>normalizeMapLocation(initial)),[mode,setMode]=useState<'approximate'|'exact'>(initial?.mode||'approximate'),[exactConsent,setExactConsent]=useState(initial?.mode==='exact');
 function changeMode(value:'approximate'|'exact'){setMode(value);setExactConsent(false);setPoint(previous=>previous?normalizeMapLocation({...previous,mode:value}):undefined);}
 return <section className="border-y border-black py-6"><h4 className="text-2xl font-black">{fr?'LA LOCALISATION':'LOCATION'}</h4><label className="mt-5 block"><span className="lg-kicker">{fr?'Quartier / secteur (facultatif)':'Neighbourhood / area (optional)'}</span><input name="district" maxLength={80} defaultValue={district||''} className="editor-input" placeholder={fr?'Ex. : Pampelonne':'E.g. Pampelonne'}/></label><label className="mt-5 block"><span className="lg-kicker">{fr?'Affichage sur la fiche publique':'Display on the public listing'}</span><select className="editor-input" value={mode} onChange={e=>changeMode(e.target.value as 'approximate'|'exact')}><option value="approximate">{fr?'Localisation approximative (recommandée)':'Approximate location (recommended)'}</option><option value="exact">{fr?'Localisation exacte':'Exact location'}</option></select></label><p className="mt-4 text-sm leading-6 text-black/60">{mode==='approximate'?(fr?'Cliquez dans le secteur de la maison : seule une zone d’environ 1 km sera publiée et enregistrée. Le point précis n’est pas conservé.':'Click in the house’s area: only a zone of roughly 1 km will be published and saved. The precise point is discarded.'):(fr?'Cliquez à l’emplacement de la maison. Le point sera visible publiquement après votre autorisation.':'Click at the house’s location. The point will be public after you authorize it.')}</p><VillaLocationMap key={mode} point={point} fr={fr} onSelect={(latitude,longitude)=>setPoint(normalizeMapLocation({mode,latitude,longitude}))}/><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p role="status" className="text-xs font-bold">{point?(mode==='approximate'?(fr?'Zone approximative sélectionnée.':'Approximate area selected.'):(fr?'Point exact sélectionné.':'Exact point selected.')):(fr?'Aucun repère : seule la commune sera affichée.':'No location selected: only the town will be shown.')}</p>{point&&<button type="button" onClick={()=>{setPoint(undefined);setExactConsent(false);}} className="text-xs font-bold underline">{fr?'Retirer le repère':'Remove location'}</button>}</div>{mode==='exact'&&point&&<label className="mt-5 flex gap-3 text-sm leading-6"><input required type="checkbox" checked={exactConsent} onChange={e=>setExactConsent(e.target.checked)}/>{fr?'J’autorise l’affichage public de la position exacte de cette maison.':'I authorize public display of this house’s exact location.'}</label>}<input type="hidden" name="mapLocation" value={JSON.stringify(point&&((mode==='exact'&&exactConsent)||mode==='approximate')?point:null)}/></section>;
}
