'use client';
import {useEffect,useRef,useState} from 'react';
import AvailabilityCalendar from './AvailabilityCalendar';
import {loadVillaCalendar} from '../lib/villaCalendarStore';
import {datesBlocked,type VillaCalendar} from '../lib/villaAvailability';
import {validateStayDates,stayNights} from '../lib/stayRequest';
import {parisIsoDay} from '../lib/localCalendar';
import {addDays} from '../lib/agendaCalendar';
import VillaActions from './VillaActions';
export default function VillaStayPanel({villa,today,askHref}:{villa:{id:string;name:string;guests:number;price:number;live?:boolean};today:string;askHref:string}){
 const [arrival,setArrival]=useState(''),[departure,setDeparture]=useState(''),[guests,setGuests]=useState(String(Math.min(2,villa.guests))),[error,setError]=useState('');
 const [calendar,setCalendar]=useState<VillaCalendar|null>(null),[calendarError,setCalendarError]=useState(false),[checking,setChecking]=useState(false);const lock=useRef(false);
 useEffect(()=>{let active=true;setCalendar(null);setCalendarError(false);if(villa.live)void loadVillaCalendar(villa.id).then(c=>{if(active)setCalendar(c);}).catch(()=>{if(active)setCalendarError(true);});return()=>{active=false;};},[villa.id,villa.live]);
 async function submit(e:React.FormEvent<HTMLFormElement>){if(!villa.live){const invalid=validateStayDates({arrival,departure,guests},villa.guests,parisIsoDay());if(invalid){e.preventDefault();setError(invalid);}return;}e.preventDefault();if(lock.current)return;const invalid=validateStayDates({arrival,departure,guests},villa.guests,parisIsoDay());if(invalid){setError(invalid);return;}lock.current=true;setChecking(true);setError('');try{const current=await loadVillaCalendar(villa.id);setCalendar(current);setCalendarError(false);if(datesBlocked(current,arrival,departure)){setError('Ces dates comprennent une nuit bloquée. Choisissez une autre période.');return;}window.location.assign(`/villa/${villa.id}/contact?${new URLSearchParams({arrival,departure,guests})}`);}catch(e){if(e instanceof Error&&e.message==='CALENDAR_NOT_CONFIGURED')window.location.assign(`/villa/${villa.id}/contact?${new URLSearchParams({arrival,departure,guests})}`);else setError('Impossible de vérifier le calendrier. Réessayez dans un instant.');}finally{lock.current=false;setChecking(false);}}
 const nights=stayNights(arrival,departure);
 return <div id="demande-sejour" className="scroll-mt-6 border-t-4 border-[var(--lg-blue)] bg-[#f5f5f3] p-6 md:p-7"><p className="lg-kicker">VOTRE SÉJOUR / {villa.name}</p><p className="mt-5 text-4xl font-black tracking-[-.055em]">{villa.price?`${villa.price.toLocaleString('fr-FR')} €`:'Prix sur demande'}</p><p className="mt-2 text-xs font-semibold text-black/50">{villa.price?"À partir de / semaine · tarif à confirmer selon vos dates":"Devis selon vos dates et votre séjour"}</p>{calendar?.enabled&&<AvailabilityCalendar calendar={calendar} today={today}/>}<p className="mt-5 text-xs leading-5 text-black/55">{calendarError?'Calendrier indisponible pour le moment.':calendar?.enabled?'Calendrier renseigné par le propriétaire. Les nuits ouvertes restent à confirmer.':'Disponibilités à confirmer auprès du propriétaire.'}</p><form action={`/villa/${villa.id}/contact`} method="get" onSubmit={e=>void submit(e)} className="mt-7"><div className="grid grid-cols-2 gap-3"><label className="block text-xs font-bold">Arrivée<input required type="date" name="arrival" value={arrival} min={today} onChange={e=>{setArrival(e.target.value);if(departure&&departure<=e.target.value)setDeparture('');setError('');}} className="mt-2 w-full min-w-0 border border-black/20 bg-white px-2 py-3"/></label><label className="block text-xs font-bold">Départ<input required type="date" name="departure" value={departure} min={arrival?addDays(arrival,1):addDays(today,1)} onChange={e=>{setDeparture(e.target.value);setError('');}} className="mt-2 w-full min-w-0 border border-black/20 bg-white px-2 py-3"/></label></div><label className="mt-4 block text-xs font-bold">Voyageurs<select name="guests" value={guests} onChange={e=>setGuests(e.target.value)} className="mt-2 w-full border border-black/20 bg-white p-3">{Array.from({length:villa.guests},(_,i)=><option key={i} value={i+1}>{i+1} {i===0?'voyageur':'voyageurs'}</option>)}</select></label>{nights>0&&<p className="mt-4 text-sm font-semibold">{nights} {nights===1?'nuit':'nuits'} · {guests} voyageurs</p>}{!error&&datesBlocked(calendar,arrival,departure)&&<p role="status" className="mt-4 text-sm text-red-700">Ces dates comprennent une nuit bloquée.</p>}{error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}<button disabled={checking} className="lg-btn mt-5 w-full border-[var(--lg-blue)] bg-[var(--lg-blue)] text-white">{checking?'Vérification…':'Demander les disponibilités →'}</button></form><p className="mt-4 text-xs leading-5 text-black/50">Sans engagement ni paiement. Les disponibilités et le prix final seront confirmés avant réservation.</p><div className="mt-6 border-t border-black/15 pt-5"><VillaActions id={villa.id} name={villa.name} contactHref={`/villa/${villa.id}/contact`} askHref={askHref} hideContact/></div></div>;
}
