import VillaLocationMap from './VillaLocationMap';
import Link from 'next/link';
import VillaGallery from './VillaGallery';
import VillaStayPanel from './VillaStayPanel';
import {destinations,placesInDestination} from '../data/destinations';
import {amenityOptions} from '../lib/listingAssistant';
import type {VillaListing} from '../lib/villaListing';
export default function VillaDetail({villa,today,preview=false,locale='fr'}:{villa:VillaListing;today:string;preview?:boolean;locale?:'fr'|'en'}){
 const fr=locale==='fr',t=(a:string,b:string)=>fr?a:b;
 const description=(!fr&&villa.descriptionEn)||villa.description;
 const title=(!fr?villa.titleEn:villa.titleFr)||villa.name;
 const highlights=(!fr?villa.highlightsEn:villa.highlights)||[];
 const town=destinations.find(d=>d.name===villa.location),nearby=town?placesInDestination(town).slice(0,3):[];
 const ask=`Je regarde ${villa.name} à ${villa.location}, pour un séjour de ${villa.guests} voyageurs maximum. Aide-moi à choisir des plages, restaurants et activités dans cette commune.`;
 return <div className="pb-24 md:pb-0">
 <section className="lg-shell pb-9 pt-8 md:pt-12"><p className="lg-kicker text-[var(--lg-blue)]">{villa.location} / GOLFE DE SAINT-TROPEZ</p><h1 className="mt-5 max-w-full break-words text-[clamp(3rem,12vw,8rem)] font-black uppercase leading-[.85] tracking-[-.065em] [overflow-wrap:anywhere]">{villa.name}</h1><p className="mt-6 text-sm font-semibold text-black/55">{villa.guests} {t('voyageurs','guests')} · {villa.bedrooms} {t('chambres','bedrooms')} · {villa.bathrooms} {t('salles de bain','bathrooms')}</p></section>
 <section className="lg-shell"><VillaGallery name={villa.name} photos={villa.photos} locale={locale}/></section>
 <section className="lg-shell py-10 md:py-16"><div className="grid gap-12 lg:grid-cols-[minmax(0,1fr)_360px] lg:gap-16"><div>
 <nav aria-label={t('Dans cette fiche','On this page')} className="flex flex-wrap gap-5 border-y border-black py-5 text-xs font-bold"><a href="#la-maison">{t('La maison','The home')}</a><a href="#equipements">{t('Équipements','Amenities')}</a><a href="#le-secteur">{t('Le secteur','The area')}</a><a href="#annonceur">{t('Votre interlocuteur','Your contact')}</a></nav>
 <section id="la-maison" className="scroll-mt-8 py-10"><p className="lg-kicker text-[var(--lg-blue)]">{t('LA MAISON','THE HOME')}</p><h2 className="mt-5 text-4xl font-black leading-tight tracking-[-.04em] md:text-5xl">{title}</h2><p className="mt-6 whitespace-pre-line text-lg font-medium leading-8 text-black/65">{description||t('La présentation de cette maison sera complétée par son annonceur.','The advertiser will complete this home’s description.')}</p>{highlights.length>0&&<ul className="mt-8 grid gap-3 sm:grid-cols-2">{highlights.map((h,i)=><li key={i} className="border-l-2 border-[var(--lg-blue)] pl-4 text-sm font-bold leading-6">{h}</li>)}</ul>}<div className="mt-9 grid grid-cols-3 border-y border-black"><Fact value={String(villa.guests)} label={t('Voyageurs maximum','Maximum guests')}/><Fact value={String(villa.bedrooms)} label={t('Chambres','Bedrooms')}/><Fact value={String(villa.bathrooms)} label={t('Salles de bain','Bathrooms')}/></div></section>
 <section id="equipements" className="scroll-mt-8 border-t border-black py-10"><p className="lg-kicker text-[var(--lg-blue)]">{t('LES ÉQUIPEMENTS','AMENITIES')}</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em]">{t('Ce que propose la maison.','What the home offers.')}</h2>{villa.amenities.length>0?<ul className="mt-6 grid gap-3 sm:grid-cols-2">{villa.amenities.map(a=><li key={a} className="border border-black/15 p-4 font-semibold"><span className="mr-3 text-[var(--lg-blue)]" aria-hidden="true">✓</span>{fr?(amenityOptions.find(([en])=>en===a)?.[1]||({'Heated pool':'Piscine chauffée','Sea view':'Vue mer','Quiet setting':'Cadre calme'} as Record<string,string>)[a]||a):a}</li>)}</ul>:<p className="mt-5 text-black/60">{t('Les équipements seront précisés par l’annonceur.','Amenities will be specified by the advertiser.')}</p>}<p className="mt-5 text-sm leading-6 text-black/50">{t('Pour un besoin précis — lit bébé, accès adapté ou animaux — indiquez-le dans votre demande.','Mention any specific needs — a cot, accessible facilities or pets — in your enquiry.')}</p></section>
 <section id="le-secteur" className="scroll-mt-8 border-t border-black py-10"><p className="lg-kicker text-[var(--lg-blue)]">{t('LE SECTEUR','THE AREA')} / {villa.location}</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em]">{t('La maison, puis le Golfe.','The home, then the Gulf.')}</h2>{(villa.beachDistance!==undefined||villa.saintTropezDistance!==undefined)&&<><div className="mt-6 grid grid-cols-2 gap-4">{villa.beachDistance!==undefined&&<Fact value={`${villa.beachDistance} km`} label={t('Distance indiquée des plages','Stated distance from beaches')}/>} {villa.saintTropezDistance!==undefined&&<Fact value={`${villa.saintTropezDistance} km`} label={t('Distance indiquée de Saint-Tropez','Stated distance from Saint-Tropez')}/>}</div><p className="text-xs leading-6 text-black/50">{t('Distances indiquées par l’annonceur. Les temps de trajet varient avec la circulation.','Distances supplied by the advertiser. Travel times vary with traffic.')}</p></>}<div className="mt-7"><h3 className="text-xl font-black">{villa.district?`${villa.district} · ${villa.location}`:villa.location}</h3>{villa.mapLocation?<><p className="mt-3 text-sm leading-6 text-black/60">{villa.mapLocation.mode==='approximate'?t('Localisation approximative : la zone indique le secteur de la maison. L’adresse sera à convenir avec le propriétaire après confirmation du séjour.','Approximate location: this area indicates the house’s neighbourhood. Arrange the address with the owner after confirming your stay.'):t('Position exacte publiée avec l’autorisation du propriétaire.','Exact location published with the owner’s authorization.')}</p><VillaLocationMap point={villa.mapLocation} fr={fr}/></>:<p className="mt-3 text-sm leading-6 text-black/60">{t('La commune est renseignée. Le propriétaire précisera l’emplacement en réponse à votre demande.','The town is provided. The owner will clarify the location when responding to your enquiry.')}</p>}</div>{town&&<Link href={`/${locale}/destinations/${town.slug}`} className="lg-btn mt-6">{t('Découvrir','Explore')} {town.name} →</Link>}{nearby.length>0&&<div className="mt-7 divide-y divide-black/15 border-y border-black/15">{nearby.map(p=><Link key={p.id} href={`/${locale}/place/${p.id}`} className="flex justify-between gap-4 py-4 text-sm font-semibold"><span>{p.name}</span><span aria-hidden="true">↗</span></Link>)}</div>}</section>
 <section id="annonceur" className="scroll-mt-8 border-t border-black py-10"><p className="lg-kicker text-[var(--lg-blue)]">{t('VOTRE INTERLOCUTEUR','YOUR CONTACT')}</p><div className="mt-5 flex items-start gap-5"><div className="flex h-16 w-16 shrink-0 items-center justify-center bg-[#071D2B] text-2xl font-black text-white" aria-hidden="true">{villa.announcer?.name.trim().slice(0,1).toUpperCase()||'LG'}</div><div><p className="text-xs font-bold uppercase tracking-wider text-black/50">{villa.announcer?(villa.announcer.kind==='agency'?t('Agence / conciergerie','Agency / concierge'):t('Propriétaire','Owner')):'LE GOLFE'}</p><h2 className="mt-2 text-2xl font-black">{villa.announcer?.name||t('À votre écoute pour ce séjour.','Here to help with your stay.')}</h2></div></div><p className="mt-5 text-sm leading-7 text-black/60">{t('Décrivez vos dates, votre groupe et vos attentes. Les disponibilités, le prix final, les frais et les conditions sont à confirmer avant toute réservation.','Tell us your dates, group and expectations. Availability, final price, fees and terms must be confirmed before booking.')}</p></section>
 <section className="border-t border-black py-9"><p className="lg-kicker">{t('AVANT LE SÉJOUR','BEFORE YOUR STAY')}</p><div className="mt-5 divide-y divide-black/15">{[[t('Quel est le prix pour mes dates ?','What is the price for my dates?'),t('Le tarif affiché est un prix de départ par semaine. Demandez un devis précisant les prestations, frais et conditions.','The listed rate is a starting price per week. Ask for a quote detailing services, fees and terms.')],[t('La demande réserve-t-elle la maison ?','Does an enquiry book the home?'),t('Non. La demande est sans engagement ni paiement. Une confirmation du gestionnaire est nécessaire.','No. The enquiry has no commitment or payment. Confirmation from the manager is required.')]].map(([q,a])=><details key={q} className="py-5"><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-4 text-sm leading-7 text-black/60">{a}</p></details>)}</div></section>
 </div><aside className="lg:sticky lg:top-6 lg:self-start">{preview?<div className="border-t-4 border-[var(--lg-blue)] bg-[#f5f5f3] p-7"><Price villa={villa}/><h2 className="mt-7 text-2xl font-black">{t('Demander les disponibilités','Request availability')}</h2><p className="mt-5 text-sm leading-7 text-black/60">{t('L’aperçu présente votre fiche voyageur. Le formulaire de demande sera accessible sur la fiche mise en ligne.','This preview shows your guest page. Enquiries will be available on the published page.')}</p><span className="mt-6 block border border-black/20 p-4 text-center text-xs font-bold">{t('APERÇU — AUCUN ENVOI','PREVIEW — NO SUBMISSION')}</span></div>:<VillaStayPanel villa={villa} today={today} askHref={`/${locale}/ask?shortlist=${encodeURIComponent(ask)}`}/>}</aside></div></section>
 {!preview&&<div className="fixed inset-x-0 bottom-0 z-30 flex items-center justify-between gap-4 border-t border-black/15 bg-white px-5 py-4 md:hidden"><div><p className="text-lg font-black">{villa.price?`${villa.price.toLocaleString('fr-FR')} €`:'Sur demande'}</p><p className="text-[10px] text-black/50">{villa.price?'À partir de / semaine':''}</p></div><a href="#demande-sejour" className="lg-btn border-[var(--lg-blue)] bg-[var(--lg-blue)] text-white">Choisir mes dates →</a></div>}
 </div>;
}
function Fact({value,label}:{value:string;label:string}){return <div className="py-6 pr-3"><p className="text-3xl font-black">{value}</p><p className="mt-2 text-xs text-black/50">{label}</p></div>;}
function Price({villa}:{villa:VillaListing}){return <><p className="text-4xl font-black tracking-tight">{villa.price?`${villa.price.toLocaleString('fr-FR')} €`:'Prix sur demande'}</p>{villa.price>0&&<p className="mt-2 text-xs text-black/50">À partir de / semaine</p>}</>;}
