import {isIsoDay,formatCalendarDay} from './agendaCalendar';
export const inquiryStatuses=['new','reviewing','replied','closed'] as const;
export type InquiryStatus=typeof inquiryStatuses[number];
export type HostInquiry={id:string;listing_id:string;name:string;email:string;phone:string;arrival:string;departure:string;guests:number;message:string;status:InquiryStatus;owner_notes:string;created_at:string;updated_at:string;propertyName:string;location:string};
export type HostStay={id:string;guest:string;property:string;arrival:string;departure:string;guests:number;status:'brief'|'planning'|'confirmed';sourceInquiryId?:string;message?:string;location?:string};
export function inquiryLabel(status:InquiryStatus,fr=true){return ({new:fr?'Nouvelle':'New',reviewing:fr?'À traiter':'In review',replied:fr?'Réponse effectuée':'Replied',closed:fr?'Clôturée':'Closed'})[status];}
export function parseInquiry(value:unknown):HostInquiry|null{
 if(!value||typeof value!=='object')return null;const r=value as Record<string,unknown>;
 if(['id','listing_id','name','email','arrival','departure','message','created_at','updated_at','owner_notes'].some(k=>typeof r[k]!=='string'))return null;
 if(!inquiryStatuses.includes(r.status as InquiryStatus)||!isIsoDay(r.arrival as string)||!isIsoDay(r.departure as string)||(r.departure as string)<=(r.arrival as string)||!Number.isInteger(r.guests)||(Number(r.guests)<1||Number(r.guests)>100))return null;
 const joined=r.villa_listings as {payload?:{name?:unknown;location?:unknown}}|null;
 return {id:r.id as string,listing_id:r.listing_id as string,name:r.name as string,email:r.email as string,phone:typeof r.phone==='string'?r.phone:'',arrival:r.arrival as string,departure:r.departure as string,guests:r.guests as number,message:r.message as string,status:r.status as InquiryStatus,owner_notes:r.owner_notes as string,created_at:r.created_at as string,updated_at:r.updated_at as string,propertyName:typeof joined?.payload?.name==='string'?joined.payload.name:'Maison',location:typeof joined?.payload?.location==='string'?joined.payload.location:''};
}
const searchText=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function filterInquiries(rows:HostInquiry[],status:InquiryStatus|'all',query:string){const q=searchText(query.trim());return rows.filter(r=>(status==='all'||r.status===status)&&(!q||searchText(`${r.name} ${r.propertyName} ${r.location}`).includes(q)));}
export function briefFromInquiry(r:HostInquiry,demo=false):HostStay{return {id:`${demo?'demo-':''}inquiry-stay-${r.id}`,sourceInquiryId:`${demo?'demo:':''}${r.id}`,guest:r.name,property:r.propertyName,location:r.location,arrival:r.arrival,departure:r.departure,guests:r.guests,message:r.message,status:'brief'};}
export function inquiryReply(r:HostInquiry,fr=true){const subject=fr?`Votre demande pour ${r.propertyName}`:`Your enquiry for ${r.propertyName}`;const body=fr?`Bonjour ${r.name},\n\nMerci pour votre demande pour ${r.propertyName}, du ${formatCalendarDay(r.arrival,'fr')} au ${formatCalendarDay(r.departure,'fr')}, pour ${r.guests} voyageur(s).\n\n`:`Hello ${r.name},\n\nThank you for your enquiry for ${r.propertyName}, from ${formatCalendarDay(r.arrival,'en')} to ${formatCalendarDay(r.departure,'en')}, for ${r.guests} guest(s).\n\n`;return `mailto:${encodeURIComponent(r.email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;}
export function briefAsk(stay:HostStay,fr=true){return fr?`Prépare un séjour à ${stay.property}${stay.location?' à '+stay.location:''} du ${stay.arrival} au ${stay.departure} pour ${stay.guests} voyageurs. Propose des plages, restaurants et activités adaptés à ces dates.`:`Plan a stay at ${stay.property}${stay.location?' in '+stay.location:''} from ${stay.arrival} to ${stay.departure} for ${stay.guests} guests. Suggest beaches, restaurants and activities for these dates.`;}
export function demoInquiries(today:string):HostInquiry[]{const stamp=today+'T12:00:00.000Z';return [{id:'demo-family',listing_id:'demo-house',name:'Famille exemple',email:'demo@example.test',phone:'',arrival:today,departure:new Date(Date.parse(today+'T12:00:00Z')+7*86400000).toISOString().slice(0,10),guests:4,message:'Nous venons avec deux enfants. Nous aimerions une maison avec piscine et des idées de sorties en famille.',status:'new',owner_notes:'',created_at:stamp,updated_at:stamp,propertyName:'Maison de démonstration',location:'Ramatuelle'},{id:'demo-friends',listing_id:'demo-house',name:'Groupe exemple',email:'demo@example.test',phone:'',arrival:today,departure:new Date(Date.parse(today+'T12:00:00Z')+3*86400000).toISOString().slice(0,10),guests:6,message:'Un séjour entre amis, avec des restaurants et une sortie en mer.',status:'reviewing',owner_notes:'Vérifier les dates avant de proposer un devis.',created_at:stamp,updated_at:stamp,propertyName:'Maison de démonstration',location:'Ramatuelle'}];}
