export const locales = ["en", "fr"] as const;
export type Locale = (typeof locales)[number];
export function isLocale(value: string): value is Locale { return locales.includes(value as Locale); }
export const ui = {
 en:{guide:"The intelligent local guide · Golfe de Saint-Tropez",hero:"Your way into the Golfe.",intro:"Tell us what you're looking for. We'll help you find the right places, stays and people around Saint-Tropez.",ask:"Ask Le Golfe",house:"Find a house",explore:"Explore the Golfe",choices:"Not more choices. Better ones.",fit:"LE GOLFE is built around fit: who a place is good for, when it works, and what you should know before choosing it.",stay:"Houses & villas",stayDesc:"Matched to the way you want to stay.",guideTitle:"Know where to go.",guideDesc:"A local guide organised around fit, not rankings. Practical facts are desk-checked; LE GOLFE physical verification will be added progressively.",all:"ALL",backGuide:"All of the guide",best:"BEST FOR",know:"GOOD TO KNOW",notIdeal:"NOT IDEAL FOR",tags:"DNA / TAGS",verification:"Verification status",desk:"Desk-researched · physical verification pending",verified:"Verified by LE GOLFE",right:"Is this right for you?",rightDesc:"The final guide will match this profile against your stay, priorities and context — rather than treating every place as equally relevant.",askTitle:"Tell us what you have in mind.",askDesc:"Local intelligence that connects houses, tables, beaches, services, events and practical updates around the stay you actually want.",placeholder:"Two families, five kids, somewhere calm for lunch near Pampelonne...",try:"TRY ASKING",preview:"LE GOLFE TAKE",previewText:"Your request is matched against the guide, stays, events and local context to build a more coherent plan.",exploreGuide:"Explore guide",matchHouse:"Match a house"},
 fr:{guide:"Le guide local intelligent · Golfe de Saint-Tropez",hero:"Votre porte d’entrée sur le Golfe.",intro:"Dites-nous ce que vous recherchez. Nous vous aidons à trouver les bonnes adresses, les bonnes maisons et les bonnes personnes autour de Saint-Tropez.",ask:"Ask Le Golfe",house:"Trouver une maison",explore:"Explorer le Golfe",choices:"Moins de choix. De meilleurs choix.",fit:"LE GOLFE est construit autour de la compatibilité : pour qui un lieu est adapté, quand il fonctionne et ce qu'il faut savoir avant de le choisir.",stay:"Maisons & villas",stayDesc:"Sélectionnées selon votre manière de séjourner.",guideTitle:"Savoir où aller.",guideDesc:"Un guide local organisé autour de la pertinence, pas des classements. Les informations pratiques sont vérifiées à distance ; la vérification physique LE GOLFE sera ajoutée progressivement.",all:"TOUT",backGuide:"Tout le guide",best:"IDÉAL POUR",know:"BON À SAVOIR",notIdeal:"MOINS ADAPTÉ POUR",tags:"DNA / TAGS",verification:"Statut de vérification",desk:"Recherche documentaire · vérification physique à venir",verified:"Vérifié par LE GOLFE",right:"Est-ce fait pour vous ?",rightDesc:"À terme, LE GOLFE confrontera ce profil à votre séjour, vos priorités et votre contexte, plutôt que de considérer toutes les adresses comme équivalentes.",askTitle:"Dites-nous ce que vous avez en tête.",askDesc:"Une intelligence locale qui relie maisons, tables, plages, services, événements et informations pratiques autour du séjour que vous voulez vraiment.",placeholder:"Deux familles, cinq enfants, un déjeuner au calme près de Pampelonne...",try:"EXEMPLES",preview:"LE GOLFE TAKE",previewText:"Votre demande est confrontée au guide, aux séjours, à l'agenda et au contexte local pour construire un plan plus cohérent.",exploreGuide:"Explorer le guide",matchHouse:"Trouver une maison"}
} as const;
export const categoryFR: Record<string,{name:string;description:string}> = {
 eat:{name:"Restaurants",description:"Des tables choisies selon le moment, les personnes et l'ambiance."}, beach:{name:"Plages & beach clubs",description:"Où se baigner, s'installer, venir avec les enfants ou rester jusqu'au coucher du soleil."}, sea:{name:"Bateaux & mer",description:"Journées en mer, escapades côtières et façons de découvrir le Golfe depuis l'eau."}, do:{name:"À faire",description:"Marchés, domaines, balades et expériences qui méritent du temps."}, services:{name:"Services utiles",description:"Chefs, chauffeurs, garde d'enfants et professionnels qui facilitent le séjour."}, wellness:{name:"Bien-être & sport",description:"Sport, récupération et séances privées autour du Golfe."}, party:{name:"Bars & nightlife",description:"Du premier verre au dernier morceau : pubs, dîners-clubs et nuits tardives autour du Golfe."}, places:{name:"Villages & secteurs",description:"Comprendre où séjourner avant de choisir une maison."}
};
