import {villas} from '../data/villas';
import {isIsoDay} from './agendaCalendar';
export type RequestStatus='draft'|'sent'|'unconfirmed'|'legacy';
export type LocalRequest={id:string;villaId:string;villaName:string;location:string;name:string;email:string;phone:string;arrival:string;departure:string;guests:string;message:string;status:RequestStatus;updatedAt:string};
export const REQUEST_HISTORY_KEY='le-golfe-request-history';
export function parseHistory(raw:string|null):LocalRequest[]{if(!raw)return [];const data=JSON.parse(raw);if(!Array.isArray(data))throw new Error('Invalid history');return data.filter((x):x is LocalRequest=>Boolean(x&&typeof x==='object'&&typeof x.id==='string'&&typeof x.villaId==='string'&&typeof x.villaName==='string'&&['draft','sent','unconfirmed','legacy'].includes(x.status)&&['location','name','email','phone','arrival','departure','guests','message','updatedAt'].every(k=>typeof x[k]==='string')&&isIsoDay(x.arrival)&&isIsoDay(x.departure)&&x.departure>x.arrival));}
export function upsertHistory(items:LocalRequest[],item:LocalRequest){return [item,...items.filter(x=>x.id!==item.id)].slice(0,100);}
export function legacyHistory(raw:string|null):LocalRequest[]{if(!raw)return [];const values=JSON.parse(raw);if(!Array.isArray(values))throw new Error('Invalid legacy history');return values.flatMap((x,i)=>{if(!x||typeof x!=='object'||!isIsoDay(x.arrival)||!isIsoDay(x.departure)||x.departure<=x.arrival)return [];const villa=villas.find(v=>v.id===x.villaId||v.name===x.villaName);return [{id:`legacy:${String(x.id??i)}`,villaId:villa?.id||'',villaName:String(x.villaName||'Maison'),location:villa?.location||'',name:String(x.name||''),email:String(x.email||''),phone:String(x.phone||''),arrival:x.arrival,departure:x.departure,guests:String(x.guests||''),message:String(x.message||''),status:'legacy' as const,updatedAt:''}];});}
export function readHistory(){const current=parseHistory(localStorage.getItem(REQUEST_HISTORY_KEY));return [...current,...legacyHistory(localStorage.getItem('azurkey_requests')).filter(x=>!current.some(y=>y.id===x.id))].slice(0,100);} 
export function saveLocalRequest(item:LocalRequest){localStorage.setItem(REQUEST_HISTORY_KEY,JSON.stringify(upsertHistory(readHistory(),item)));window.dispatchEvent(new Event('le-golfe:requests'));}
export function deleteLocalRequest(id:string){if(id.startsWith('legacy:')){const old=JSON.parse(localStorage.getItem('azurkey_requests')||'[]');localStorage.setItem('azurkey_requests',JSON.stringify(old.filter((x:{id?:unknown},i:number)=>`legacy:${String(x.id??i)}`!==id)));}localStorage.setItem(REQUEST_HISTORY_KEY,JSON.stringify(readHistory().filter(x=>x.id!==id)));window.dispatchEvent(new Event('le-golfe:requests'));}
export function statusLabel(status:RequestStatus,fr=true){return ({draft:fr?'Brouillon':'Draft',sent:fr?'Enregistrée':'Recorded',unconfirmed:fr?'Envoi non confirmé':'Submission unconfirmed',legacy:fr?'Statut inconnu':'Unknown status'})[status];}
