import {isIsoDay} from './agendaCalendar';
export type BlockedPeriod={start:string;end:string};
export type VillaCalendar={listing_id:string;enabled:boolean;blocks:BlockedPeriod[];reserved?:BlockedPeriod[];updated_at:string};
export function validPeriod(value:unknown):value is BlockedPeriod{if(!value||typeof value!=='object')return false;const p=value as BlockedPeriod;return typeof p.start==='string'&&typeof p.end==='string'&&isIsoDay(p.start)&&isIsoDay(p.end)&&p.end>p.start;}
export function mergePeriods(periods:BlockedPeriod[]):BlockedPeriod[]{if(periods.length>200||periods.some(p=>!validPeriod(p)))throw new Error('INVALID_PERIOD');const result:BlockedPeriod[]=[];for(const p of [...periods].sort((a,b)=>a.start.localeCompare(b.start))){const last=result[result.length-1];if(last&&p.start<=last.end)last.end=last.end>p.end?last.end:p.end;else result.push({start:p.start,end:p.end});}return result;}
export function parseCalendar(value:unknown):VillaCalendar|null{if(!value||typeof value!=='object')return null;const c=value as VillaCalendar;if(typeof c.listing_id!=='string'||!/^property-[a-zA-Z0-9-]{1,100}$/.test(c.listing_id)||typeof c.enabled!=='boolean'||typeof c.updated_at!=='string'||!Number.isFinite(Date.parse(c.updated_at))||!Array.isArray(c.blocks)||c.blocks.length>200||c.blocks.some(p=>!validPeriod(p)))return null;if(c.reserved!==undefined&&(!Array.isArray(c.reserved)||c.reserved.length>200||c.reserved.some(p=>!validPeriod(p))))return null;return {listing_id:c.listing_id,enabled:c.enabled,blocks:mergePeriods(c.blocks),updated_at:c.updated_at,...(c.reserved!==undefined?{reserved:mergePeriods(c.reserved)}:{})};}
/** Night intervals: arrival included, departure excluded. Adjacent stays may share a checkout day. */
export function datesBlocked(calendar:VillaCalendar|null|undefined,arrival:string,departure:string){return !!calendar&&isIsoDay(arrival)&&isIsoDay(departure)&&departure>arrival&&[...(calendar.enabled?calendar.blocks:[]),...(calendar.reserved||[])].some(p=>arrival<p.end&&departure>p.start);}
export function calendarAllows(calendar:VillaCalendar|null|undefined,arrival:string,departure:string){return !!calendar?.enabled&&isIsoDay(arrival)&&isIsoDay(departure)&&departure>arrival&&!datesBlocked(calendar,arrival,departure);}
